### ISSUE TITLE
bug 42filechecker

### ISSUE THREAD

**Issue by cybernnal** [jgigault/42FileChecker#10]
thx for this tools
but there is always a warning with the norm he can't checka file but all's right

**Comment by jgigault** [comment]
Hello
The norminette has recently changed but I'm not able to come at school and test it with my script since I'm doing my first internship in Lyon.
Can you please show me what's output with the norminette and your work `norminette your_libft/`?

**Comment by jgigault** [comment]
I close this one. See issue number 9.
