### ISSUE TITLE
display not cleaning

### ISSUE THREAD

**Issue by simdax** [jgigault/42FileChecker#101]
On a simple Ubuntu 16.4, the screen do not clear. 

The reading becomes impossible.

Tried on Guake, Terminator, and simple xfce4-term 

maybe a hint, I have 
```
    tput: unknown terminfo capability 'cd' 
```
on the top of the screen ?

**Comment by cbcercas** [comment]
tu peux fix ca en remplacant `tput cd` par `tput ed` dans `includes/utils/utils.sh` ligne 255

**Comment by simdax** [comment]
superbe. Thank you, it works.

**Comment by jgigault** [comment]
Hello, chaud pour faire une PR? :-)

**Comment by cbcercas** [comment]
^^
