### ISSUE TITLE
Bug ou erreur de ma part ?

### ISSUE THREAD

**Issue by gdufay** [jgigault/42FileChecker#102]
Bonjour, lors des basics tests de printf, j'obtiens les erreurs suivantes :

# 0027 (int)
  ft_printf("%jx", 4294967295);
  1. (    1) -->jx<--
  2. (    8) -->ffffffff<--

# 0028 (int)
  ft_printf("%jx", 4294967296);
  1. (    1) -->jx<--
  2. (    9) -->100000000<--

# 0029 (int)
  ft_printf("%jx", -4294967296);
  1. (    1) -->jx<--
  2. (   16) -->ffffffff00000000<--

# 0030 (int)
  ft_printf("%jx", -4294967297);
  1. (    1) -->jx<--
  2. (   16) -->fffffffeffffffff<--

or quand je te test avec mon propre main :

i = ft_printf("ft : %jx\n", 4294967295);
j = dprintf(1, "real : %jx\n", 4294967295);
i = ft_printf("ft : %jx\n", 4294967296);
j = dprintf(1, "real : %jx\n", 4294967296);
i = ft_printf("ft : %jx\n", -4294967296);
j = dprintf(1, "real : %jx\n", -4294967296);
i = ft_printf("ft : %jx\n", -4294967297);
j = dprintf(1, "real : %jx\n", -4294967297);

J'obtiens les resultats suivant :

ft : ffffffff
real : ffffffff
ft : 100000000
real : 100000000
ft : ffffffff00000000
real : ffffffff00000000
ft : fffffffeffffffff
real : fffffffeffffffff

Cette erreur est apparue suite au changement de fichier d'une fonction n'intervenant meme pas dans ce cas, ainsi, je me demande s'il s'agit d'un bug ou alors d'une erreur de ma part au vu des resultats identiques

Merci par avance et desole du derangement

**Comment by Seluj78** [comment]
As tu reussi a resoudre ton probleme ?

**Comment by gdufay** [comment]
Oui, desole de ne pas avoir prevenu plus tot, cela provenait bien de mon code, dprintf m'empechait seulement de visualiser l'erreur, en utilisant printf j'ai pu corriger
Encore desole du derangement

**Comment by Seluj78** [comment]
Super pas de probleme ! Bon courage pour la suite
