### ISSUE TITLE
Display still not cleaning

### ISSUE THREAD

**Issue by Alkanna** [jgigault/42FileChecker#104]
Self explanatory, display is still not cleaning properly since last update, you can only use the checker if you remember the right keybinds, otherwise you can't see most of them.

**Comment by cbcercas** [comment]
What os are you using?
my PR #103  to fix #101 broke this can you try this:
in includes/utils/utils.sh line 255
replace `tput ed` by `tput cd`

**Comment by Alkanna** [comment]
It works, thanks !

**Comment by cbcercas** [comment]
Ok, I don't have a mac, so  can you try my new fix here https://github.com/cbcercas/42FileChecker/tree/bugfix--display-not-cleaning

**Comment by Seluj78** [comment]
I just tried your new fix @cbcercas on a cluster and it doenst work :/
![screen shot 2017-12-26 at 1 24 09 pm](https://user-images.githubusercontent.com/4641317/34356668-18935fe0-ea40-11e7-9e2e-13843384e105.png)

**Comment by jgigault** [comment]
Maybe:

```
tput ed 2>/dev/null
tput cd 2>/dev/null
```

If both works on different platforms?

**Comment by wbaridon** [comment]
On cluster your fix duplicate the line (white line then green line). But if you put:
`   tput cup 0 0
    tput cd 2>/dev/null`
It's okay.

**Comment by jgigault** [comment]
je viens de push ccf8d390e6a6e9bd86be1f758b9ae711a3bcabf3
peux-tu me dire si ça fix le soucis stp ?
sur d'autres terminaux la requête `cd` ne fonctionne pas (#101)

**Comment by Seluj78** [comment]
@jgigault Je viens de tester sur `Ubuntu bash pour windows` avec oh-my-zsh`, commande `bash ./42FileChecker` et aucun probleme, a par la lenteur de mon term mais c'est client side.

Si j'y penses je teste demain a 42

**Comment by Seluj78** [comment]
#84
