### ISSUE TITLE
UI errors

### ISSUE THREAD

**Issue by andrei78987** [jgigault/42FileChecker#106]
this checker have very bigs errors with his interfaces

**Comment by jgigault** [comment]
I just pushed ccf8d390e6a6e9bd86be1f758b9ae711a3bcabf3
can you tell me if it fixes the issue please?

**Comment by Seluj78** [comment]
Any update on that @andrei78987 ?

**Comment by andrei78987** [comment]
yes now all is ok good work man


2018-01-01 22:50 GMT+02:00 Jules Lasne (jlasne) <notifications@github.com>:

**Comment by Seluj78** [comment]
#84
