### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by mbelaloui** [jgigault/42FileChecker#107]
l'interface graphique depuis peu ne fonctionne pas bien, le rafraîchissement de la page ne s'effectue pas merci

**Comment by jgigault** [comment]
je viens de push ccf8d390e6a6e9bd86be1f758b9ae711a3bcabf3
peux-tu me dire si ça fix le soucis stp ?

**Comment by mbelaloui** [comment]
Bonjourla je pourrai pas te dire je suis pas a l'ecole, mais je te dirrai ca des demain ou apres demain, si non y'a t'il un moyen pour que ca marche sur linux <ubuntu> a la maison ??? j'ai essayer un truques mais ca ne l'a pas fait. merci bonne fin d'annee.
   Le dimanche 31 décembre 2017 à 09:47:51 UTC+1, Jean-Michel Gigault <notifications@github.com> a écrit :  
 
 
je viens de push ccf8d39
peux-tu me dire si ça fix le soucis stp ?

**Comment by Seluj78** [comment]
@mbelaloui As tu reesaye depuis le dernier push ? Chez moi sur ubuntu bash windows ca marche

**Comment by mbelaloui** [comment]
Bonjour et bonne année
    alors je vien d'essayer a la maison <machine sous ubuntu>, le premier bug reporter n'existe plus, cependant voila ce qui ce passe si je l'essaye sur mon projet libft qui a l'ecole est passé a 42filechecker, le teste de ( Jtoty, et celui de mdemon) et la moulinette. les premieres testes niquele (image 1 et 2), arriver au makefile il me dis qu'il ya un problemes puis l'interface deconne (image 3), puis rien ne passe apres (image 4), quand je veux voir le log il me fait (could not get a file descriptor referring to the console image 5)

Belaloui Mehdi Aissa. 

    Le lundi 1 janvier 2018 à 21:55:33 UTC+1, Jules Lasne (jlasne) <notifications@github.com> a écrit :  
 
 
@mbelaloui As tu reesaye depuis le dernier push ? Chez moi sur ubuntu bash windows ca marche

**Comment by Seluj78** [comment]
Alors, tu ne peux malheureusement pas mettre d'images quand tu reponds par email, donc au lieu de repondre directement si tu pouvais cliquer sur `view it on GitHub` ca serai mieux :p Ensuite, sans les screens je peux rien faire sauf pour le dernier, cette erreur de FD, c'est open qui merde 1 fois sur 2 en fonction de ton desktop, de ton OS etc... sur OSX aucun probleme, mais sinon ca a tendance a merder

**Comment by mbelaloui** [comment]
voila les images :  
![1](https://user-images.githubusercontent.com/22576736/34480528-3d899716-efad-11e7-9a5f-a40102d23996.png)
![2](https://user-images.githubusercontent.com/22576736/34480532-44cfe232-efad-11e7-87d8-b0e9e22a9dce.png)
![3](https://user-images.githubusercontent.com/22576736/34480535-46a20946-efad-11e7-96bd-e509dda17982.png)
![4](https://user-images.githubusercontent.com/22576736/34480536-49ade7b8-efad-11e7-9c6a-8af4a44ac418.png)
![5](https://user-images.githubusercontent.com/22576736/34480585-923523a2-efad-11e7-8105-27572685f5a3.png)
du coup en ce qui concerne le fd ya moyen de reparer ca ?? <je suis sous ubuntu desktop unity>

**Comment by Seluj78** [comment]
https://stackoverflow.com/questions/42463929/couldnt-find-a-file-descriptor-referring-to-the-console-on-ubuntu-bash-on-win 💋

**Comment by jgigault** [comment]
@Seluj78 There is still a UI bug here, maybe it is not a good idea to close this issue, we should:
-> either keep it opened
-> or create a new issue about to the UI problem (and refer it here)

**Comment by Seluj78** [comment]
The thing is, this issue is related to #106, #84 and #104 plus this one. So yeah, your choice, either we close all the others and keep one or create a new one
