### ISSUE TITLE
Did the update break GNL tests?

### ISSUE THREAD

**Issue by m-rezgui** [jgigault/42FileChecker#109]
Depuis la mise a jour, tous les test sur GNL (peut être sur d'autres projets) passe en OK alors qu'ils sont faux.

**Comment by Seluj78** [comment]
@m-rezgui peut tu preciser de quelle mise a jour tu parles, une date ou un commit ? Ca nous aiderai plus :)

**Comment by Seluj78** [comment]
Perso je viens de tester avec [mon propre GNL](https://github.com/Seluj78/Get_Next_Line)  et aucun probleme, a part d'affichage et de compatibilite (cf. #110) mais rien de choquant par rapport au tests

![screenshot_1](https://user-images.githubusercontent.com/4641317/34471074-16df65f0-ef3f-11e7-8ab0-39c7e3c448e0.png)

**Comment by m-rezgui** [comment]
Depuis le dernier commit, mais j'ai rien dit ça fonctionne. (je ne sais pourquoi, par exemple j'avais bon au bonus multi fd, alors que je ne l'ai pas gerer).

**Comment by Seluj78** [comment]
Parce que ton BUF_SIZE etait set a `1` :p Bon courage pour la suite :)

**Comment by m-rezgui** [comment]
Merci.

Le 2 janv. 2018 08:48, "Jules Lasne (jlasne)" <notifications@github.com> a
écrit :
