### ISSUE TITLE
Une erreur de norme

### ISSUE THREAD

**Issue by numerbistriplebis** [jgigault/42FileChecker#11]
Sur la libft quand on fait un check alors que dans le fichier il signale un warning. Je te mets le fichier ci dessous, et gg pour ton 42filechecker cest du bon boulot !!
[mynorminette copy.txt](https://github.com/jgigault/42FileChecker/files/52289/mynorminette.copy.txt)

**Comment by jgigault** [comment]
Merci :)
J'essaie de comprendre ce qui se passe.. D'où vient cette ligne à la fin ? :/
Est-ce qu'avec la nouvelle norminette on a le droit de faire ´ norminette ./fichier1.c ./dossier/fichier2.c ./fichier3.h ´. Par exemple ? 
Qu'est-ce que cela donne si tu le fais à la main avec la liste des fichiers en argument (pas de dossier) ? Please

**Comment by numerbistriplebis** [comment]
Si je le fait a la main avec norminette ./ ou norminette * il me dit que tout est bon sauf évidemment pour le fichier auteur et makefile. J'essaie de t'envoyer plus d'info demain je suis plus à  l'école 

Envoyé de mon iPhone

**Comment by jgigault** [comment]
I close this one. See issue number 9.
