### ISSUE TITLE
nm compatibility Ubuntu bash for windows

### ISSUE THREAD

**Issue by Seluj78** [jgigault/42FileChecker#110]
Very unlikely case., I might be the only one to use this but might report it anyway :)

 `-m` doesn't seem to be supported on `nm` on ubuntu bash for windows

![screenshot_1](https://user-images.githubusercontent.com/4641317/34471074-16df65f0-ef3f-11e7-8ab0-39c7e3c448e0.png)

**Comment by CamilleBC** [comment]
You're not the only one :)

![screenshot from 2018-01-03 12-28-01](https://user-images.githubusercontent.com/11173924/34518868-bdb6d79e-f081-11e7-90c8-6b52e11d27a4.png)

**Comment by florenzo-42** [comment]
Same for me...

**Comment by Seluj78** [comment]
It's really weird because I can't find a man page that references the `-m` option :/ @jgigault ?

**Comment by Seluj78** [comment]
After further research, the `-m` option is only available on Darwin based computers
