### ISSUE TITLE
Issue with Ubuntu

### ISSUE THREAD

**Issue by yann120** [jgigault/42FileChecker#125]
Hi, 
Thanks for your amazing work!
I try to make it work on my PC with ubuntu 18.04 but i have troubles.
I installed the 2 packages required on linux as written in the readme.
I can compile my libft files with make but 42filechecker says that the compilation has failed.
Here is a screenshot : https://ibb.co/geM82q
Also when i try to see more, like if I press 2, I have an error : Impossible d'obtenir le descripteur de fichier faisant référence à la console

Thanks!

**Comment by jgigault** [comment]
Hello @yann120 
Thanks for the issue, and sorry for the long delay of my response.
Did you resolve the issue with compilation? If yes, can you tell me how you did it?
You can find more log information by manually opening files starting with a dot `.` at the root directory of the installation of 42FC

**Comment by yann120** [comment]
Hi,
thanks for your reply.
I changed my PC for a Mac for other reasons so I have no more problems with 42FC.
But I didn't fix it
