### ISSUE TITLE
Libft - SIGABORT

### ISSUE THREAD

**Issue by lbarthon** [jgigault/42FileChecker#126]
La moulinette me donne un SIGABORT sur la 2nd part, dommage alors que je passais tous les tests du 42FC :/ De plus, le strsplit n'est pas testé avec un caractère absent de la chaîne, ce qui fait planter mon programme.
Cependant, le 42FC est quand même un super outil :3

**Comment by jgigault** [comment]
Salut @lbarthon 
Merci pour ton message :-)

1. Difficile de savoir ce que fait la moulinette, alors malheureusement ce sont des choses qui arrivent !

2. Je t'invite à ouvrir des issues sur les scripts de test de la libft pour suggérer (et expliquer en détail) l'absence de test sur strplit avec le cas que tu as mentionné:
- https://github.com/alelievr/libft-unit-test
- https://github.com/yyang42/moulitest
- https://github.com/QuentinPerez/Maintest
