### ISSUE TITLE
Fillit checker in 42filechecker

### ISSUE THREAD

**Issue by Twitting** [jgigault/42FileChecker#130]
Hey, we have used your precious checker to check our project, got KO, and found a mistake: it's a tetromino sample look like that:
##..
##..
....
..,.
that test might be useful to be added

**Comment by jgigault** [comment]
Hello @Twitting and thank you for your message.
As you noticed, tests for this projects are external to 42FC, then you should open a issue on the relevant repository: https://github.com/anisg/fillit_checker
If you know a better script to test fillit, let me know!
