### ISSUE TITLE
Libft static declaration warning

### ISSUE THREAD

**Issue by znatno** [jgigault/42FileChecker#131]
After fixing a warning in ft_atoi.c is still showing in checker and file by a line which doesn't have this function. Code is starting from 15th line
```
static int	getnb(char const *s, int i, int sym, int nb)
{
	while (s[i] >= '0' && s[i] <= '9')
	{
		if (9223372036854775807 - nb < s[i] - '0')
		{
			if (sym == -1)
				return (0);
			else
				return (-1);
		}
		nb = nb * 10 + s[i] - '0';
		i++;
	}
	if (sym == -1)
		nb = -nb;
	return (nb);
}
```

.mystatic consists that
`ft_atoi.c (line 16) : getnb() should be declared as static`

**Comment by jgigault** [comment]
Hello @znatno and sorry for my delayed answer.

Is your issue reproductible?
Does the script 42FC displaying "1 warning(s)"? 
Did you reload the file `.mystatic`? Because when you open this file, then re-run the tests, you have to close and re-open the log file `.mystatic`.

Thanks for your help

**Comment by znatno** [comment]
Hey @jgigault
It was because there was one more file what wasn't edited with the same name in included directory. And checker was also checking including directories. So I just was confused by situation that I edited the file but nothing changed.
Thank you
