### ISSUE TITLE
Fillit test case error_03

### ISSUE THREAD

**Issue by Manmeet2018** [jgigault/42FileChecker#140]
This should not be in the error file directory  because this is a valid case.
Please update the checker and put the test case in valid cases directory. 😠

**Comment by Seluj78** [comment]
@Manmeet2018 You can open the Pull request yourself if you wish.

**Comment by Seluj78** [comment]
And this is not the correct repository. Please see https://github.com/anisg/fillit_checker

**Comment by jgigault** [comment]
Dear @Manmeet2018 
You are mentioning a behavior that is not intended by 42FC but fillit_checker
Please open an issue on this repository: https://github.com/anisg/fillit_checker/issues
