### ISSUE TITLE
Executable non trouvé fillit

### ISSUE THREAD

**Issue by CyberDuck79** [jgigault/42FileChecker#143]
Le test supprime l’exécutable avant le fillit file checker, je fait les tests du makefile dans le même ordre et l’exécutable est toujours la.
j'ai vu une autre issue ouverte avec le même problème il y a deux ans mais la "solution" donnée n'a rien a voir (ajouter -f a la regle rm ne change rien du tout ça force juste la suppression... clairement ce n'est pas ça qui a résolu son problème !).
le makefile :
CC			=	gcc
CFLAGS		=	-Wall -Wextra -Werror

NAME		=	fillit

LIBRARY		=	libft/libft.a

SOURCES		=	fillit.c file.c pieces.c position.c utils.c

OBJECTS		=	$(SOURCES:.c = .o)

all: $(NAME)

$(NAME): $(OBJECTS) $(LIBRARY)
	@$(CC) $(CFLAGS) -o $@ $^
	@echo $(GREEN)  [√]     [Program Successfully Compiled!]
$(LIBRARY):
	@make -C libft/

clean:
	@make clean -C libft/

fclean: clean
	@rm libft/libft.a
	@rm $(NAME)

re: fclean all

GREEN = "\033[1;32m"

**Comment by jgigault** [comment]
Salut @CyberDuck79 
Je ne suis pas sûr de bien saisir le problème.
Que remets-tu en cause : Les tests de règle du Makefile ? Si oui, peux-tu me fournir plus d'explications : Est-ce la règle "make re" ou "make fclean", etc.
Merci d'avance

**Comment by jgigault** [comment]
Closing this one due to lack of answer
