### ISSUE TITLE
is not a bug, and a recommendation 

### ISSUE THREAD

**Issue by danjos91** [jgigault/42FileChecker#145]
if make GNL whit massive, moulinette gives set_fault if you don't have this for example:
static char *example[value];
if (fd > value)
return (-1);
A lot of students don't do it and actually don't knot the reason of seg_fault because 42filechecker gives all ok, and this is the reason, we a some workmates tested it.

**Comment by jgigault** [comment]
Hello @dannyjose 
Do you mean GNL reading a very large amounts of files?
How many files should be tested for a relevant test?

**Comment by jgigault** [comment]
I am closing this one due to lack of answer
