### ISSUE TITLE
Pft abort

### ISSUE THREAD

**Issue by alexeyvilmost** [jgigault/42FileChecker#150]
A -> PFT (https://github.com/gavinfielder/pft)
  [|] cp: /unit_tests.42fc.c: No such file or directory
Warning: dirname() expects exactly 1 parameter, 2 given in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 9

Warning: dirname() expects exactly 1 parameter, 2 given in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 10

Warning: file_get_contents(/42fc.conf): failed to open stream: No such file or directory in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 16

Warning: fopen(/options-config.ini.override): failed to open stream: Permission denied in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 18

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 19

Warning: fclose() expects parameter 1 to be resource, boolean given in /Users/pallspic/Tests/pft/configurations/42fc/configure_42fc.php on line 20
PFT has aborted

**Comment by jgigault** [comment]
Hello @alexeyvilmost 
Please report this issue on the relevant repository :-)
https://github.com/gavinfielder/pft
