### ISSUE TITLE
fillit checker

### ISSUE THREAD

**Issue by Sahbetdin** [jgigault/42FileChecker#154]
Hello!
Thank you for this great checker!

I would like to mention one moment regarding fillit project.
Yesterday we delivered our fillit project with my mate.
We succeeded in second trial.
The problem was with invalid tetramino

#...
.#..
..#.
...#

Our fillet program passed all checker tests.
But when peer appeared and started checking according to the procedure, our program finished with segmentation fault. 

Could you pay attention to validation of tetraminos? Possibly, checker doesn't process thoroughly. 

Thank you!

Regards,
Mansur /btrifle/

**Comment by jgigault** [comment]
Hello @Sahbetdin 
Tests for fillit project are not internal to 42FC, but delivered by the script https://github.com/anisg/fillit_checker
I assume it is no longer maintained, so do you now a script that could be integrated in 42FC to take your issue into account?

**Comment by Sahbetdin** [comment]
Hello!No, thank you.I think we can close it. Regards,Mansur 15.12.2019, 16:10, "Jean-Michel Gigault" <notifications@github.com>:Hello @Sahbetdin
Tests for fillit project are not internal to 42FC, but delivered by the script https://github.com/anisg/fillit_checker
I assume it is no longer maintained, so do you now a script that could be integrated in 42FC to take your issue into account?
