### ISSUE TITLE
GNL Error

### ISSUE THREAD

**Issue by overedge** [jgigault/42FileChecker#18]
Salut le moulitest ne passe pas pour GNL 
j'ai 4 erreur basique mais quand je corrige une faute de norme ( donc rien avoir ) bah sa change mes erreurs.

il m'en reste une puis je refais une erreur de norme pour tester et biim 4 erreurs

**Comment by jgigault** [comment]
Hello,
Je ne suis pas sûr de bien comprendre...

Qu'entends-tu par "le moulitest ne passe pas pour GNL" ?
Si tu fails aléatoirement sur les tests, c'est qu'il y a peut-être un bug de comportement dans l'une de tes fonctions, qui résulte en un comportement indéfini selon l'état de la mémoire
