### ISSUE TITLE
Leaks - besoin des perms admins

### ISSUE THREAD

**Issue by ThisIsMac47** [jgigault/42FileChecker#19]
La nouvelle version demande les droits admin pour s'executer donc elle fail quand on l'execute a l'ecole, peut etre repasse a l'ancienne methode

**Comment by jgigault** [comment]
Hello,
Il n'y pas eu de changement pour l'exécution de la commande `leaks`.
De mémoire, la demande mot de passe arrivait déjà de temps en temps à l'école. Et certains mac ne permettent pas d'avoir les droits suffisants pour GDB ou d'autres utilitaires.
Cela t'arrive t'il sur n'importe quel poste de l'école ?

**Comment by ThisIsMac47** [comment]
J'ai juste vu l'erreur sur le mac que j'utilise tous les jours, plusieurs gens ont report le prob sur slack aussi, et vu que sa me le faisait pas avant ..

**Comment by jgigault** [comment]
Et en renseignant ton mot de passe, que se passe t-il exactement ?

Peux-tu tester cette commande stp: 
```bash
leaks $(ps | awk 'NR == 2 {print}' | cut -d" " -f1)
```

Est-ce que le mot de passe t'est demandé et quelle est la sortie ?

**Comment by ThisIsMac47** [comment]
Ok donc entre temps ils ont passes les macs sous el capitan et j'ai plus de probleme donc faudrait trouver quelqu'un qui l'a encore.

**Comment by Popoyoyo** [comment]
Bonjour.

Alors soit j'ai encore le problème des droits d'admin... soit je ne sait absolument pas utiliser Leaks. Les 2 sont possible. voici la liste des commandes et réponse que j'obtiens:

e1r8p14% leaks Test_get_nxt
An admin user name and password is required to enter Developer Mode.
Admin user name (opicher): opicher
Password:
leaks[10018]: unable to get permission to examine process.
leaks[10018]: leaks cannot find any existing process you have access to which has a name like 'Test_get_nxt'; try running with `sudo`.
e1r8p14% sudo leaks Test_get_nxt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
opicher is not in the sudoers file.  This incident will be reported.
e1r8p14% leaks $(ps | awk 'NR == 2 {print}' | cut -d" " -f1) Test_get_nxt
An admin user name and password is required to enter Developer Mode.
Admin user name (opicher): opicher
Password:
leaks[10069]: unable to get permission to examine process.
leaks[10069]: leaks cannot find any existing process you have access to which has a name like 'Test_get_nxt'; try running with `sudo`.
e1r8p14%

**Comment by jgigault** [comment]
Les droits d'admin semblent demandés aléatoirement et par période à l'école.
Cette issue n'a plus de raison d'être :-)
