### ISSUE TITLE
get_next_line leaks test cannot compile

### ISSUE THREAD

**Issue by F1orin** [jgigault/42FileChecker#2]
![screen shot 2015-01-05 at 19 25 33](https://cloud.githubusercontent.com/assets/979700/5617557/81e1a552-9510-11e4-83e4-b17b890b48a9.png)

After the last update, leaks test began to fail.
Details at https://profile.intrav2.42.fr/users/fbicher

**Comment by jgigault** [comment]
Thanks for your help!
