### ISSUE TITLE
moulinette&forbidden function bug bonus

### ISSUE THREAD

**Issue by owinckle** [jgigault/42FileChecker#24]
ne compile pas.

**Comment by jgigault** [comment]
sur quel projet please ?
qu'appelles-tu moulinette ? le moulitest ?
les logs ("more info") te disent quelque chose ?

**Comment by owinckle** [comment]
Desole, enfaite le bug etait de mon cote.

2016-02-01 18:58 GMT+01:00 Jean-Michel Gigault <notifications@github.com>:

**Comment by jgigault** [comment]
Ok
