### ISSUE TITLE
moulitest ne trouve pas #<libft.h>

### ISSUE THREAD

**Issue by LIMachi** [jgigault/42FileChecker#25]
Comme le dit le titre, je viens de tester une nouvelle version de ma libft avec 42FileChecker, et j'ai utilisé des dossiers pour ranger les .h, .o et .c (respectivement "include", "src", "OBJ").
Tous les test ce passent bien, même ceux de unit-test, mais moulittest (son Makefile) ne prend pas en compte la possibilité de l'utilisation d'un sous dossier pour libft.h.
Éventuellement, on devrait utiliser un libft.h propre a moulitest et ne pas utiliser celui de l'élève (je ne pense pas que ça change grand chose pour les tests).

**Comment by jgigault** [comment]
Hello @LIMachi 

Je ne suis pas d'accord sur le fait qu'on pourrait imaginer de proposer un header générique pour ce genre de test car **libft** est aussi l'occasion pour un élève d'apprendre à créer un fichier de header correct. Les fichiers sources sont indissociables des fichiers de header, et il faut apprendre à faire les deux correctement, c'est la base.

Pour ce qui est de l'emplacement du fichier dans le rendu du projet, voici ce que dit le sujet du projet :

```
Vous devez rendre un fichier C par fonction à réaliser ainsi qu’un fichier libft.h
qui contiendra tous leurs prototypes ainsi que les macros et les typedefs dont
vous pourriez avoir besoin. Tous ces fichiers devront se trouver à la racine de votre
dépot.
```

De même que pour **get_next_line** le sujet précise par exemple - depuis peu - que la macro du buffer **devra impérativement s’appeler BUFF_SIZE** sans quoi la moulinette (et non le moulitest) ne compilera pas votre projet.

Il me semble normal qu'un framework de test comme le moulitest, censé être dans la ligne pédagogique de 42, ne compile pas si le projet ne respecte pas les **rares** règles du sujet (Si on supprime les préambules, les sujets ne font rarement plus de deux pages !).

Après, tout dépend de l'auteur du framework et de son avis sur la question ! Je t'invite à créer un ticket sur le dépôt en question :-)
