### ISSUE TITLE
Test sur strcmp && strncmp libft

### ISSUE THREAD

**Issue by kkuette** [jgigault/42FileChecker#26]
Apres test du moulitest + unit test m'ayant pas pris en comptes certaines erreurs;

exemple : strcmp("", " ") || strncmp("", " ");
strcmp("aaa", "") || strncmp("aaa", "");

28/28 unit-test+moulitest != 26/28 moulinette;

**Comment by kkuette** [comment]
while ((s1[i] != '\0' || s2[i] != '\0') && tmp == 0)

**Comment by jgigault** [comment]
Hello @kkuette
Je t'invite à ouvrir une issue sur chacun des deux repos, car cela ne concerne pas le code contenu dans 42FileChecker :-)
Merci en tout cas !
