### ISSUE TITLE
FT_PRINTF - Cant launch errors checks

### ISSUE THREAD

**Issue by Tolo789** [jgigault/42FileChecker#27]
Hi,
I really found useful the 42FileChecker for the GNL and now I wanted to use it even for my printf. So I started by launching your basic tests but I keep getting this same error and I dont know how to fix it: 

# 0001 
  ft_printf("");
includes/ft_printf.sh: line 166: printf: includes/ft_printf.sh: line 119: ./tmp/ft_printf_0: No such file or directory: invalid number
  1. (    0) -->includes/ft_printf.sh: line 119: ./tmp/ft_printf_0: No such file or directory<--
  2. (    0) --><--

...

# 0197 (unsigned int)
  ft_printf("@moulitest: %.5u", "42");
includes/ft_printf.sh: line 166: printf: includes/ft_printf.sh: line 119: ./tmp/ft_printf_u: No such file or directory: invalid number
  1. (    0) -->includes/ft_printf.sh: line 119: ./tmp/ft_printf_u: No such file or directory<--
  2. (   17) -->@moulitest: 00042<--

However, both the makefile test and the Moulitest (both launched within the 42FileCheker) work perfectly.
Do you have any idea on how to fix this ??

Thank you in advance,

cmutti

**Comment by jgigault** [comment]
Hello @Tolo789 

Could you send me your project by mail (jgigault@student.42.fr) or give me an access to an online repository ?
I would like to test on my computer

Thanks

Jean-Michel

**Comment by Tolo789** [comment]
Yep,here it comes!




----Messaggio originale----

Da: Jean-Michel Gigault <notifications@github.com>

Data: 11-feb-2016 16.38

A: "jgigault/42FileChecker"<42FileChecker@noreply.github.com>

Cc: "Claudio Mutti"<cmutti@student.42.fr>

Ogg: Re: [42FileChecker] FT_PRINTF - Cant launch errors checks (#27)




Hello @Tolo789 


Could you send me your project by mail (jgigault@student.42.fr) or give me an access to an online repository ?

I would like to test on my computer


Thanks


Jean-Michel

**Comment by jgigault** [comment]
I did not received your files
Please send me an email to jgigault@student.42.fr :-) 
(and do not reply)

**Comment by jgigault** [comment]
Thanks again!
