### ISSUE TITLE
Sujet et leaks

### ISSUE THREAD

**Issue by nmougino** [jgigault/42FileChecker#29]
Salut!
On a deja du te le report (<- et je suppose qu'on te dis ca souvent) (<- et ca aussi) (<-habituelement il n'y a que moi qui vais jusque la)
mais pour Get_next_line, ton test necessite d'avoir libft.h a la racine du dossier de rendu - le sujet precise que ce fichier doit etre dans le dossier libft, lui meme a la racine.
Aussi, la detection des memory leaks necessite une authentification staff helas :/ - ou autre, je ne suis pas renseigne. Mais il nous ai bien demander les id/mdp du group Developer Tools

Voila :) En esperant etre utile
cordialement
nmougino

**Comment by nmougino** [comment]
Double correction:
Le sujet demande que libft.h soit dans libft/includes
ET
les basic tests fonctionnent avec cette configuration, mais pas moulitest

**Comment by lpoujade** [comment]
C'est une issue du moulitest alors, je pense pas qu'il le corrigera ici

**Comment by jgigault** [comment]
Hello @nmougino
En effet comme le dit @lpoujade : si le test "moulitest" ne compile pas pour un include de libft.h, c'est une issue qui concerne le dépôt github du moulitest mais je vais regarder de plus près tout à l'heure.
Pour les leaks et le problème d'authentification, malheureusement je n'y peux rien c'est un problème de droit lié à nos sessions à l'école. J'ai envie de te dire de le signaler au bocal si ça t'arrive systématiquement. Pour ma part, j'ai les droits 2 fois sur 3 environ mais je ne peux pas te dire pourquoi :-)
Jean-Mi
