### ISSUE TITLE
printf("% v")

### ISSUE THREAD

**Issue by frsechet** [jgigault/42FileChecker#3]
Salut,

Je ne comprends pas bien ce que tu cherches a tester dans les "basic tests" avec "% v"... ce n'est certainement pas a gerer! Man 3 printf dit:

The AltiVec Technology Programming Interface Manual also defines five additional length modifiers which can be used (in place of the conventional modifiers) for the printing of AltiVec or SSE vectors:
v           Treat the argument as a vector value, unit length will be determined by the conversion specifier (default = 16 8-bit units for all integer conversions, 4 32-bit units for floating point conversions).

Ca fait certainement partie des trucs "bizarres" dans tous les cas, et c'est meme un bonus bien relou a gerer. Es-tu bien sur que tu voulais faire cela? Si oui, tu peux expliquer un peu la demerche? Merci!

F.

**Comment by frsechet** [comment]
Ce flag reste present dans les basic tests %s! ;-)
Merci pour l'explication!

**Comment by jgigault** [comment]
Salut,
C'est que je m'exprime mal dans les descriptions de commits :/
L'absence du "s" justement fait de "% h" quelque chose de "faux", c'est tout ce que je cherche à tester.
C'est déjà fait dans la précédent test avec un espace seul mais je veux ajouter une lettre qui n'existe pas dans printf. Au départ "z" puis je me suis aperçu que ça existait, après "v" puis c'est toi qui me fait remarquer que ça existe... bref j'explore printf depuis peu comme tu le vois !
As-tu sous la main une lettre qui "n'existe" pas en tant que flag ou type de conversion ? :-)

**Comment by frsechet** [comment]
% h reste un test interessant par ailleurs, car gestion d'erreur inside (en gros, on donne des flags, des modifiers, etc. mais pas d'argument - que se passe-t-il dans ce cas?).
Le probleme de % v, c'est que le printf de c le transforme en un truc qui imprime un certain nombre de caracteres a l'ecran, alors que comme je ne le prends pas en compte, pour ma part j'imprime juste "v".

Tu peux essayer %Z par exemple!

**Comment by jgigault** [comment]
Oui mais l'absence de second argument ne devrait pour autant rien afficher, n'est-ce pas ?
Du moins mes tests perso ne m'ont pas afficher quoique ce soit avec la commande suivante:
printf("% v");
La conversion "% v" qui est "valide" n'a pas d'élément à convertir, donc rien n'est affiché.

As-tu observé un autre comportement ?
Car finalement ça serait aussi un test intéressant de gestion d'erreur

Merci pour le %Z :-)

**Comment by frsechet** [comment]
Essaie un printf("% v\n") pour rigoler... ;-)
Et comme on n'a pas le flag v a gerer, on n'a pas a le considerer comme un flag, donc on doit le traiter comme le %Z par exemple, mais va comparer ca avec le "% v" de printf... D'autant plus que dans le sujet, on pourrait aussi considerer %Z comme une erreur et exit, et je considerais ca comme valide en correction pour ma part, car ce n'est pas un flag valide de printf d'apres le man (et pour preuve, la compilation avec les flags me jette, d'ailleurs, sauf a prendre des precautions type passer un ft_strdup("%Z") comme premier argument de printf). Le sujet precise de gerer les erreurs de facon sensible... c'est sujet a interpretation!

**Comment by jgigault** [comment]
Ok je vois. En effet %Z affiche bien "Z", et si on ne gère pas %v on devrait afficher "v".

Pour éviter une erreur de compilation telle que tu la décris, j'ai trouvé la parade "printf(fmt, NULL);"
J'avais essayé avec "strdup" avec le même résultat d'erreur, mais pas avec "ft_strdup".

Merci encore pour ta contribution

**Comment by frsechet** [comment]
Mais sinon, tu as laisse le "% v" dans les basic tests de %s... (c'etait le sens de mon 2e message)!
Ce test etait a 2 endroits: basic tests et basic tests %s.

**Comment by jgigault** [comment]
Quel boulet
