### ISSUE TITLE
BUG ON CORR PRINTF

### ISSUE THREAD

**Issue by yeticoolbrothers42** [jgigault/42FileChecker#31]
for the basic test #046, 047 048 : 
# 0047 (int)
  ft_printf("@moulitest: %.x", %.0x, 0, 0); <-- wrong 
  1. (   16) -->@moulitest: 0, 0<--
  2. (   14) -->@moulitest: , <--
ty

**Comment by jgigault** [comment]
Could you explain a bit more please?

**Comment by yeticoolbrothers42** [comment]
ft_printf("@moulitest: %.x## " ##, %.0x, 0, 0); <-- wrong
ft_printf("@moulitest: %.x, %.0x## " ##, 0, 0); <-- right
