### ISSUE TITLE
erreur fichier auteur

### ISSUE THREAD

**Issue by MaximeRouff** [jgigault/42FileChecker#34]
bonjour, il y a un petit problème sur la versification du fichier auteur, 42FC ne vérifie pas si il y a des '\n' après le log.

**Comment by jgigault** [comment]
Hello @MaximeRouff 
Normalement si :/ Tu as remarqué ça à l'école ou bien sur une autre plateforme ?

```bash
  1 -> auteur
  No [Line Feed] character at the end of line
```

**Comment by MaximeRouff** [comment]
A l’école lors de ma correction :/ 

 

De : Jean-Michel Gigault [mailto:notifications@github.com] 
Envoyé : mercredi 9 mars 2016 15:48
À : jgigault/42FileChecker <42FileChecker@noreply.github.com>
Cc : MaximeRouff <maxime.rouffelaers@gmail.com>
Objet : Re: [42FileChecker] erreur fichier auteur (#34)

 

Hello @MaximeRouff <https://github.com/MaximeRouff>  
Normalement si :/ Tu as remarqué ça à l'école ou bien sur une autre plateforme ?

  1 -> auteur
  No [Line Feed] character at the end of line

**Comment by jgigault** [comment]
Tu t'es aperçu en correction que tu n'avais pas de "\n" alors que ça t'affichait vert avant c'est ça ? Navré si c'est le cas ! Tu n'utilises le FileChecker que sous Mac ?

Je viens de refaire un test et ça me vérifie bien la présence du "\n" (sous Mac)
Tu n'as peut-être pas pushé la bonne version du fichier auteur avec un "\n" non ?

(J'en ai profité pour recoder cette fonction, mais elle conserve le même fonctionnement)

**Comment by MaximeRouff** [comment]
Si il repère l’existence ou non de ’\n’ mais pas le fait qu’il y en ai plus d’un. Du moins c’est le problème qui m’es arriver

 

De : Jean-Michel Gigault [mailto:notifications@github.com] 
Envoyé : mercredi 9 mars 2016 16:25
À : jgigault/42FileChecker <42FileChecker@noreply.github.com>
Cc : MaximeRouff <maxime.rouffelaers@gmail.com>
Objet : Re: [42FileChecker] erreur fichier auteur (#34)

 

Tu t'es aperçu en correction que tu n'avais pas de "\n" alors que ça t'affichait vert avant c'est ça ? Navré si c'est le cas ! Tu n'utilises le FileChecker que sous Mac ?

Je viens de refaire un test et ça me vérifie bien la présence du "\n" (sous Mac)
Tu n'as peut-être pas pushé la bonne version du fichier auteur avec un "\n" non ?

(J'en ai profité pour recoder cette fonction, mais elle conserve le même fonctionnement)

**Comment by jgigault** [comment]
Ahh ok je n'avais pas compris, je vais rajouter ça merci !

**Comment by MaximeRouff** [comment]
C’est moi qui te remercie d’avoir pris le temps de corriger le problème :) et de nous fournir ce super outil .
