### ISSUE TITLE
42Filechecker FdF

### ISSUE THREAD

**Issue by Remaii** [jgigault/42FileChecker#38]
check de la norme sur mlx.h

ducoup la norme aime pas trop xD 
merci pour ton taf sa aide :)

**Comment by jgigault** [comment]
Hello
Je songe à supprimer FdF du 42FileChecker et à faire une section spéciale configurable pour les tests de base (norme, fonctions autorisées, auteur, etc..) et qui pourrait s'adapter à n'importe quel projet.
Il faudra effectivement que je prenne en compte ce genre de cas ! Merci
