### ISSUE TITLE
[ALIAS ERROR]

### ISSUE THREAD

**Issue by ale-batt** [jgigault/42FileChecker#4]
Salut !
Premièrement, merci pour ce projet, vraiment super utiles !
Juste, impossible d'aliasé la commande "~/42FileChecker/42FileCheacker.sh" 
sa donne des problemes d'include..
Je vais essayer de resoudre le probleme sur ma machine.
Je te tien au courent.

Cordialement,

**Comment by jgigault** [comment]
Salut

Je vais me pencher sur le sujet, en effet tous les chemins du script sont en relatifs...

**Comment by jgigault** [comment]
finally supported!
