### ISSUE TITLE
Integration with travis

### ISSUE THREAD

**Issue by dannywillems** [jgigault/42FileChecker#40]
Hi.

It will be interesting to have a way to pass arguments to the shell file to be able to use Travis.
For example
```
./42FileChecker --path=/home/travis/libft --project=libft --tests=all --no-norminette
```
will launch 42FileChecker for the libft, pass moulitest and libftunit-test, doesn't check norminette and the libft is in /home/travis/libft directory.

**Comment by jgigault** [comment]
Interesting idea as I told you on Slack :-)
It's on my TODO list

**Comment by jgigault** [comment]
In progress :-) 
https://github.com/jgigault/42FileChecker/pull/48
