### ISSUE TITLE
Bug sur Maintest qperez, pas de trace ?

### ISSUE THREAD

**Issue by Lusoline** [jgigault/42FileChecker#43]
Bonjour, je te contacte par rapport au main de test ajouté à la dernière update. En effet, je me retrouve avec une erreur de compilation ("An error occured while compiling your program") mais impossible d'obtenir la moindre trace en appuyant sur B contrairement aux autres tests (comme si je n'avais appuyé sur aucune touche). 

Merci d'avance pour ta réponse :).

******edit******
J'ai testé le main directement en le compilant avec ma libft en dehors de 42filechecker et là il n'y a aucune erreur, tout fonctionne parfaitement.

**Comment by jgigault** [comment]
Hello @Lusoline
Pourrais-tu m'envoyer ta libft sur ma boite mail student stp ?

**Comment by jgigault** [comment]
@Lusoline 
As-tu lu mon précédent message ? 
Merci

**Comment by Lusoline** [comment]
Coucou, je suis désolée j'étais absente pendant quelques jours, imprévu
familial. Je t'envoie ça dès que j'arrive à 42 :).

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-26 10:59 GMT+02:00 Jean-Michel Gigault <notifications@github.com>:

**Comment by Lusoline** [comment]
Voila, c'est envoyé :)

**Comment by jgigault** [comment]
Merci !
Erreur de ma part dans le nommage d'une fonction...

**Comment by Lusoline** [comment]
J'ai bien fait de te l'envoyer alors, merci d'avoir regardé :) Bonne
journée à toi !

2016-04-26 16:00 GMT+02:00 Jean-Michel Gigault <notifications@github.com>:
