### ISSUE TITLE
libft_unit_test

### ISSUE THREAD

**Issue by Hohenfels** [jgigault/42FileChecker#49]
The libft_unit_test compile my libft then stuck in "Running Test..."

My friends tried with my lib and it worked. It seems that I am the only one which have this issue. 

Here's a screenshot : http://www.noelshack.com/2016-40-1475519510-capture-d-ecran-2016-10-03-a-14-40-28.png

I haven't found any issue on the author's github of the libft_test_unit

Thanks.

**Comment by jgigault** [comment]
Hello @Hohenfels 
Did you get in touch with the author of the tester?
I am not sure about what to do with your issue :-)
Jean-Michel

**Comment by Hohenfels** [comment]
Salut @jgigault 
Bon je vais parler francais ca sera plus simple.

Oui c'est bon j'ai parle directement avec l'auteur et nous avons regle le probleme, c'etait du a la nouvelle mise a jours de mac "Sierra" qui a changé l'emplacement du malloc. Il a fait un fix et tout fonctionne bien

**Comment by jgigault** [comment]
Ok parfait !
