### ISSUE TITLE
[FUITE]

### ISSUE THREAD

**Issue by ale-batt** [jgigault/42FileChecker#5]
Encore salut !
Dans le moulitest, un processus continue de tournee en boucle en fond et cree des problemes
"Your system has running out of memory" 
je l'ai kill, mais voila, 
process "gnl9"

**Comment by jgigault** [comment]
salut

"gnl9" fait partie des 'basic tests' (et non du moulitest), il teste 'get_next_line' avec un file descriptor inexistant et tu dois avoir une boucle infini lors de ce test. 
tu peux regarder du côté du main de test pour essayer de ton côté : "srcs/gnl/gnl9.c"

néanmoins je vais ajouter un time out et un 'kill process' en cas de situation similaire
merci pour l'info et désolé d'avoir saturé ta machine en arrière-plan ;-)
