### ISSUE TITLE
Bug forbidden fonction

### ISSUE THREAD

**Issue by TeoWneD** [jgigault/42FileChecker#50]
apres avoir dl a partir de fb ma libft.zip, sachant que tous les tests etaient vert je lance une derniere fois le full test, la norminette ne fonctionne plus on est obligé de couper la commande, et les forbidden fonction font apparaitre une bonne vingtaine de ligne d'erreur awk: can't open file 2/libft/ft_memmove.c
 source line number 1
awk: can't open file 2/libft/ft_putstr.c
 source line number 1
awk: can't open file 2/libft/ft_lstforeach_if.c
 source line number 1
awk: can't open file 2/libft/ft_atoi.c
 source line number 1
awk: can't open file 2/libft/ft_factorial.c
 source line number 1
awk: can't open file 2/libft/ft_strsub.c
 source line number 1
awk: can't open file 2/libft/ft_lstnew.c
 source line number 1
awk: can't open file 2/libft/ft_strrchr.c
 source line number 1
awk: can't open file 2/libft/ft_putchar.c
 source line number 1
awk: can't open file 2/libft/ft_isascii.c
  8 -> forbidden functions                                                                 No forbidden function found
  9 -> moulitest (https://github.com/yyang42/moulitest_42projects)                                       Not performed
  A -> libft-unit-test (https://github.com/alelievr/libft-unit-test)                                     Not performed
  B -> Maintest (https://github.com/QuentinPerez/Maintest)                                               Not performed
 source line number 1

  1)    OK
  2)    more info: required functions
  3)    more info: bonus functions
  4)    more info: extra functions
  5)    more info: norminette
  6)    more info: static declarations
  7)    more info: makefile
  8)    more info: forbidden functions
  9)    more info: moulitest
  A)    more info: libft-unit-test
  B)    more info: Maintest

  C)    REPORT A BUG ON 42FILECHECKER
  D)    REPORT A BUG ON MOULITEST
  E)    REPORT A BUG ON LIBFT-UNIT-TEST
  F)    REPORT A BUG ON MAINTEST
  G)    BACK TO MAIN MENU

 source line number 1
awk: can't open file 2/libft/ft_strncpy.c
 source line number 1
awk: can't open file 2/libft/ft_memalloc.c
 source line number 1
awk: can't open file 2/libft/ft_strcat.c
 source line number 1
awk: can't open file 2/libft/ft_putchar_fd.c
 source line number 1
awk: can't open file 2/libft/ft_strnequ.c
 source line number 1
awk: can't open file 2/libft/ft_power.c
 source line number 1
awk: can't open file 2/libft/ft_memset.c
 source line number 1
awk: can't open file 2/libft/ft_strcmp.c
 source line number 1
awk: can't open file 2/libft/ft_memcmp.c
 source line number 1
awk: can't open file 2/libft/ft_bzero.c
 source line number 1
awk: can't open file 2/libft/ft_isprint.c
 source line number 1
awk: can't open file 2/libft/ft_putendl_fd.c
 source line number 1
awk: can't open file 2/libft/ft_memdel.c
 source line number 1
awk: can't open file 2/libft/ft_swap.c
 source line number 1
awk: can't open file 2/libft/ft_strdup.c
 source line number 1
awk: can't open file 2/libft/ft_strlcat.c
 source line number 1
awk: can't open file 2/libft/ft_tolower.c
 source line number 1
awk: can't open file 2/libft/ft_lstpush_back.c
 source line number 1
awk: can't open file 2/libft/ft_putendl.c
 source line number 1

apres avoir dit que tous les test etaient valides, bizzare.

**Comment by jgigault** [comment]
Salut @TeoWneD 
Rencontre-tu encore ce soucis ?
Jean-Michel
