### ISSUE TITLE
Inode issue with push_swap (CHECKER) Makefile

### ISSUE THREAD

**Issue by Thog** [jgigault/42FileChecker#51]
I'm getting a weird error when I'm running the makefile test during the re rule, it said that the inode haven't changed for the checker executable. I have checked multiple time and run the test outside, and the inode change so I guess it's a internal issue.

Testing Makefile https://github.com/Thog/push_swap/blob/master/Makefile

Thanks in advance, Thog.

**Comment by jgigault** [comment]
Hi @Thog 
Could you tell me on which platform do you run the filechecker?
If it is at 42 school, I know there is an issue with inode test and will fix it soon.
Jean-Michel

**Comment by Thog** [comment]
Yes I was testing it at school

**Comment by Seluj78** [comment]
@Thog We would need to know what terminal you are using

**Comment by Thog** [comment]
@Seluj78 ZSH with this configuration https://github.com/Thog/dotfiles

**Comment by Seluj78** [comment]
So i'd guess it was running on iTerm3. The inode issue is known and it seems to be random, never happened to me though to others like you it does. We'll try to fix it asap

**Comment by Seluj78** [comment]
Hey @Thog I suppose you never tried again :/

@jgigault what can I do to try and fix this ? Any idea ?Or just close the issue ?

**Comment by Seluj78** [comment]
Closed to group all the related issues in 115
