### ISSUE TITLE
42FileChecker: Author Files and makefile

### ISSUE THREAD

**Issue by davidtaohuang** [jgigault/42FileChecker#52]
Hi,

I'm a student at 42 in the U.S. and just found your 42FileChecker program It's very useful, but it doesn't recognize author files in english (spelled "author" instead of "auteur") and makefile (spelled "makefile" instead of "Makefile", though that might be on purpose on your part I guess). I just thought you would like to know since I assume more people from our campus will probably be using  it soon. Thanks!

Best,
David Huang

**Comment by jgigault** [comment]
Hello David,
Nice to hear from 42 US!
I thank you for your help and will take your issue soon into account.
Jean-Michel
