### ISSUE TITLE
Makefile .PHONY

### ISSUE THREAD

**Issue by jzck** [jgigault/42FileChecker#56]
```
CHECKING RULE: .PHONY
-> Failing rule: It should not have cleaned the binary named 'fillit'
```

Encore moi, pour les tests du makefile j'ai l'erreur ci-dessus, cependant la règle .PHONY n'a pas à être exécutée elle est là pour repérer les règles qui n'ont pas des noms de fichier : https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

**Comment by jgigault** [comment]
Salut et merci 
Je vais adapter ça et reviendrais vers toi pour que tu me confirmes le bon fonctionnement :)
