### ISSUE TITLE
42FC Isn't working well on ubuntu

### ISSUE THREAD

**Issue by ghost** [jgigault/42FileChecker#57]
The screen doesn't fully update when you type a command. Additional info also isn't displayed.

**Comment by jgigault** [comment]
What do you mean about "additional info"? Typing a number after running tests does nothing? It should open text files with logs. 

I know the problem about Ubuntu and other Linus distributions, I posted an issue a few days ago :-)

Thank you!

**Comment by jgigault** [comment]
What terminal are you using?

**Comment by DanTheFan** [comment]
First of all, thank you very much, it helps a lot. I'm using terminal. Yes a was talking about additional info. I think on linux it's the command "see", not "open". When I press a certain digit it doesn't fully update the screen.
![screemshot](https://cloud.githubusercontent.com/assets/20305798/20071677/11cf0fc2-a52e-11e6-8dda-6d8b61843b90.png)

**Comment by Seluj78** [comment]
I think this is because of the way that the ubuntu terminal handles the screen and the way 42FC is made. If you press `ESC` then scroll up you'll see it's a loop which displays the same thing over and over everytime something new is displayed

**Comment by Seluj78** [comment]
#84
