### ISSUE TITLE
ne compile pas avec libft.a

### ISSUE THREAD

**Issue by Bressack** [jgigault/42FileChecker#59]
Le 42FileChecker de get_next_line ne compile pas libft.a ... le nom du dossier libft est peu claire

bisou :D

**Comment by jgigault** [comment]
Hello

Qu'entends-tu par "le nom du dossier libft est peu clair" ?
J'ai fait une mise à jour mais je sais pas si c'était l'origine de ton problème.
Peux-tu tester et me dire stp ?

Merci

**Comment by Bressack** [comment]
erreur de ma part
