### ISSUE TITLE
42FileChecker key loop

### ISSUE THREAD

**Issue by elbekri** [jgigault/42FileChecker#64]
Si on reste appuyer sur le numpad pendant les tests le 42FileChecker commence a agir de maniere indeterminer.

**Comment by jgigault** [comment]
Pendant les tests il y a une boucle `read` par seconde, chez moi garder une touche appuyée accélère le "time out" simplement.
Quel comportement peux-tu rencontrer d'autre ?

**Comment by elbekri** [comment]
Des erreurs de normes inexistantes (+ de 900) et l'affichage qui bug dans
le terminal avec le chevauchement de l'affichage des touches qu'on spam

Le 23 nov. 2016 08:21, "Jean-Michel Gigault" <notifications@github.com> a
écrit :

**Comment by elbekri** [comment]
Cela dit c'est juste si on fait n'importe quoi  ;) en soit le 42FileChecker
fonctionne bien sa ne fait pas tout mais sa reste une très bonne base de
test
