### ISSUE TITLE
Libft should give a timeout after 10 seconds

### ISSUE THREAD

**Issue by jraleman** [jgigault/42FileChecker#65]
For the libft, I found in the hard way :( that Moulinette will give a timeout if the following takes more than 10 seconds to finish this:

`make clean && make && make fclean && make && make re && ls -l libft.a`

This means that even though, everything is correct, if you add a lot of extra functions (in my case, about 35), it will time out and give you a zero, no matter what.

**Comment by Seluj78** [comment]
Please send us your makefile And we'll take a look at it

**Comment by jraleman** [comment]
Sure, here it's. This one is without the 35 extra functions.

```
CC      = gcc
CFLAGS  = -Wall -Wextra -Werror
AR      = ar rc
RANLIB  = ranlib

NAME    = libft.a
HEAD    = libft.h
SRCS    = ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
ft_isdigit.c ft_isprint.c ft_itoa.c ft_lstadd.c ft_lstdel.c ft_lstdelone.c \
ft_lstiter.c ft_lstmap.c ft_lstnew.c ft_memalloc.c ft_memccpy.c ft_memchr.c \
ft_memcmp.c ft_memcpy.c ft_memdel.c ft_memmove.c ft_memset.c ft_putchar_fd.c \
ft_putchar.c ft_putendl_fd.c ft_putendl.c ft_putnbr_fd.c ft_putnbr.c \
ft_putstr_fd.c ft_putstr.c ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c \
ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c ft_striteri.c \
ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c ft_strmapi.c ft_strncat.c \
ft_strncmp.c ft_strncpy.c ft_strnequ.c ft_strnew.c ft_strnstr.c ft_strrchr.c \
ft_strsplit.c ft_strstr.c ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c \
ft_iswspace.c ft_isspace.c ft_wordlen.c ft_wordcount.c ft_nbrlen.c

OBJS    = $(SRCS:.c=.o)

.PHONY: all, clean, fclean, re

all: $(NAME)

$(NAME):
		@$(CC) $(CFLAGS) -c $(SRCS)
		@$(AR) $(NAME) $(OBJS)
		@$(RANLIB) $(NAME)
		@echo "[INFO] Library [$(NAME)] created!"

clean:
		@rm -f $(OBJS)
		@echo "[INFO] Objects removed!"

fclean: clean
		@rm -f $(NAME)
		@echo "[INFO] Library [$(NAME)] removed!"

re:		fclean all
```

**Comment by Seluj78** [comment]
Sadly, We can't do anything about this on the school's side. The moulinette is kept up and running and updated by the Dev Team at the school. You should contact the peda to talk about it.

I think a way to have it pass would be to have like 5 extra functions, validate your project and then add the 30 functions to your lib afterwards.

By doing this you would significantly reduce the time that takes the `make` command to compile all your data.

On 42FC though, i'll add an issue tagged with enhancement to get something done about it like if extra func > 10 : timeout = 60 seconds.

PS : You should put your .PHONY at the end of the Makefile

Have a nice day ! 😄

**Comment by jgigault** [comment]
@jraleman Thank you for having noticed this issue. My colleagues and I also have experienced this issue, even if our Makefiles did compile in less than 10 seconds.
Unfortunately, the fact is that we cannot reproduce the technical conditions of the moulinette that makes our Makefiles to exceed the timeout of 10 seconds. Because it is remotely executed on 42's servers and because of conditions that differs on date and time depending on the server availabality.
