### ISSUE TITLE
test leaks sur get_next_line

### ISSUE THREAD

**Issue by Bressack** [jgigault/42FileChecker#66]
C'est pas vraiment un bug, mais plutôt une astuce. Sur les postes de 42, le system demande les identifiants administrateur. Mais on les a pas. Donc j'ai trouvé une solution, c'est de rentrer les identifiant : exam exam 👍  et ça marche :)

**Comment by Seluj78** [comment]
Exact, pour fix l'issue des leaks, faire un `leaks top` puis rentrer exam exam en identifiant et mot de passe

**Comment by jgigault** [comment]
Before closing this issue, we should create a section "known issues" in the README that links to wiki pages and explain why and how to.

**Comment by Seluj78** [comment]
Alright I'll try to do something like that
