### ISSUE TITLE
Makefile error 're'

### ISSUE THREAD

**Issue by 42fortytwo42** [jgigault/42FileChecker#67]
It seems that there is an error caused by same inode unchanged.

I give you the info... maybe i am wrong on my Makefile, but i have some doubt on it.

CHECKING RULE: re
-> Failing rule: It should have compiled again the binary named 'libftprintf.a' (inode unchanged)

good luck :0

**Comment by aloisLSW42** [comment]
same thing for me

**Comment by Seluj78** [comment]
Can you guys send me your makefiles ?

**Comment by aloisLSW42** [comment]
` 13 NAME = libft.a
 14 INC = includes/libft.h
 15 CC = gcc
 16 FLAGS += -Wall -Wextra -Werror -I$(INC)
 17
 18 SRCS = ft_memset.c \
 19     ft_memcpy.c\
 20     ft_memccpy.c\
 21     ft_memmove.c\
 22     ft_memchr.c\
 23     ft_memcmp.c\
 24     ft_strlen.c\
 25     ft_strdup.c\
 26     ft_strcpy.c\
 27     ft_strncpy.c\
 28     ft_strcat.c\
 29     ft_strncat.c\
 30     ft_strlcat.c\
 31     ft_strchr.c\
 32     ft_strrchr.c\
 33     ft_strstr.c\
 34     ft_strnstr.c\
 35     ft_strcmp.c\
 36     ft_strncmp.c\
 37     ft_atoi.c\
 38     ft_isalpha.c\
 39     ft_isdigit.c\
 40     ft_isalnum.c\
 41     ft_isascii.c\
 42     ft_isprint.c\
 43     ft_toupper.c\
 44     ft_tolower.c\
 45     ft_memalloc.c\
 46     ft_memdel.c\
 47     ft_strnew.c\
 48     ft_strdel.c\
 49     ft_strclr.c\
 50     ft_striter.c\
 51     ft_striteri.c\
 52     ft_strmap.c\
 53     ft_strmapi.c\
 54     ft_strequ.c\
 55     ft_strnequ.c\
 56     ft_strsub.c\
 57     ft_strjoin.c\
 58     ft_strtrim.c\
 59     ft_strsplit.c\
 60     ft_itoa.c\
 61     ft_putchar.c\
 62     ft_putstr.c\
 63     ft_putendl.c\
 64     ft_putnbr.c\
 65     ft_putchar.c\
 66     ft_putstr_fd.c\
 67     ft_putendl_fd.c\
 68     ft_putnbr_fd.c
 69
 70 OBJS = $(SRCS:.c=.o)
 71
 72 RM = rm -rf
 73
 74 $(NAME): $(INC)
 75         $(CC) $(FLAGS) -c $(SRCS)
 76         ar rc $(NAME) $(OBJS)
 77         ranlib $(NAME)
 78
 79 all: $(NAME)
 80
 81 clean:
 82         $(RM) $(OBJS)
 83
 84 fclean: clean
 85         $(RM) $(NAME)
 86
 87 re: fclean all`

**Comment by Seluj78** [comment]
Well as for this one, it's pretty obvious

it asks for : `Failing rule: It should have compiled again the binary named 'libftprintf.a'`
But in your case @aloisLSW42 your makefile compiles a libft.a

**Comment by Seluj78** [comment]
@jgigault je suis allé voir @aloisLSW42 ert impossible de fix son erreur de inode, meme avec mon makefile qui ne relink pas

**Comment by jgigault** [comment]
TODO: provide a custom C program to retreive inode:

https://stackoverflow.com/questions/9480568/find-inode-number-of-a-file-using-c-code

**Comment by Seluj78** [comment]
Closed to group all the related issues in 115

**Comment by mykolasm** [comment]
I'm getting the same error despite my makefile looking the same:

CHECKING RULE: re
-> Failing rule: It should have compiled again the binary named 'libft.a' (inode unchanged

**Comment by Seluj78** [comment]
@mykolasm are you at 42 tomorrow ?

**Comment by Seluj78** [comment]
(opening the issue again was a mistake sorry)
