### ISSUE TITLE
libft timeout on to many extra functions

### ISSUE THREAD

**Issue by Seluj78** [jgigault/42FileChecker#71]
Add something like so :

if EXTRA_FUNC_COUNT > 10
then set MAKE_TIMEOUT = 60 seconds

**Comment by runiArnsbjornson** [comment]
for me, i had more than 15 extra functions , and no time out. not sure the issue is really the number of extra functions

**Comment by jgigault** [comment]
@Seluj78 This is not a reliable test, as I commented on #65

**Comment by Seluj78** [comment]
Aright then we need to find a solution
