### ISSUE TITLE
42FileChecker won't open on Ubuntu

### ISSUE THREAD

**Issue by arthusc** [jgigault/42FileChecker#73]
Hello, I can't launch 42FileChecker, I am currently on Ubuntu version 16.04.4.

When I use sh 42FileChecker.sh I get these errors : 

42FileChecker.sh: 13: 42FileChecker.sh: function: not found
42FileChecker.sh: 15: 42FileChecker.sh: Bad substitution

When I use zsh 42FileChecker.sh I get this one : 

42FileChecker.sh:38: = not found

My bash version is the following : 
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
Licence GPLv3+

**Comment by Seluj78** [comment]
Are you in 42's school right now ? If so message me on slack and i'll come see you.

What command are you doing to execute it ? :)

**Comment by Seluj78** [comment]
As we saw, you need to launch 42FileChecker.sh with`bash` or `sh`, one of them will work
