### ISSUE TITLE
Executable non trouvé fillit

### ISSUE THREAD

**Issue by linor78** [jgigault/42FileChecker#76]
Le script nous dit ne pas trouver l'exécutable fillit alors que les tests du makefile sont bons.on a fait les tests de makefile dans le meme ordre que le script et on a bien un executable a la fin des tests.

**Comment by Seluj78** [comment]
Envoie nous le resutalt d'un `cat Makefile` et d'un `ls -R` a la racine de ton dossier du fillit :)

**Comment by linor78** [comment]
J'ai trouvé l'erreur, il fallait ajouter -f a mon 
rm $(NAME)

**Comment by Seluj78** [comment]
Super bonne journée et bon courage :)
