### ISSUE TITLE
Pourquoi dans fillit le fichier auteur est déclaré comme optionnel ?

### ISSUE THREAD

**Issue by Dededede4** [jgigault/42FileChecker#78]
Salut !

Dans le projet fillit, on n'a rien qui dit qu'il faut un fichier auteur.
Au contraire, on voit dans le PDF : 

```
Si vous voulez ajouter un fichier externe à votre programme (autrement dit : qui ne
sera pas compilé), il devra impérativement s’appeler extern_file.txt, et devra
se trouver à la racine de votre dépôt.
```
Donc le comportement de 42FC est mauvais. Il faut virer la ligne « fichier auteur » lors du test, et mettre « extern file » en rouge.

Voili voilou,
Émile PRÉVOT

**Comment by Seluj78** [comment]
Comme ecrit sur 42FC, le fichier auteur est optionel. Apres verification avec la pedagogie, le fichier auteur pour le projet fillit n'est pas demande, donc optionel et passera sans probleme avec la mouliette

**Comment by Dededede4** [comment]
« vu avec la pédago » signifie : 
« bah si on lui demande pas, c est que c est pas demande »
« @jlasne c’est pas demander tu peuxle mettre mais c’est pas demander »

Pour moi il n'y a pas de doute.
