### ISSUE TITLE
Mon exécutable est présent mais disparait quand je lance le file checker

### ISSUE THREAD

**Issue by Rivoll** [jgigault/42FileChecker#80]

**Comment by Seluj78** [comment]
Peut on avoir plus de précisions ? Quel projet ? Et 42FC recompile tout donc pas d'histoire d'exécutable normalement

**Comment by Rivoll** [comment]
J'ai compris pourquoi en fait.

My bad déso.

________________________________
De : Jules Lasne (jlasne) <notifications@github.com>
Envoyé : jeudi 22 décembre 2016 20:38:16
À : jgigault/42FileChecker
Cc : Rivoll; Author
Objet : Re: [jgigault/42FileChecker] Mon exécutable est présent mais disparait quand je lance le file checker (#80)


Peut on avoir plus de précisions ? Quel projet ? Et 42FC recompile tout donc pas d'histoire d'exécutable normalement

-

**Comment by Seluj78** [comment]
Okay super,

Passe une bonne soirée et de bonnes fêtes !

**Comment by Rivoll** [comment]
Merci bonne fête Jules :)

________________________________
De : Jules Lasne (jlasne) <notifications@github.com>
Envoyé : vendredi 23 décembre 2016 16:33:30
À : jgigault/42FileChecker
Cc : Rivoll; Author
Objet : Re: [jgigault/42FileChecker] Mon exécutable est présent mais disparait quand je lance le file checker (#80)


Okay super,

Passe une bonne soirée et de bonnes fêtes !

-
