### ISSUE TITLE
Issues with static function prototyping

### ISSUE THREAD

**Issue by JanWalsh91** [jgigault/42FileChecker#81]
Hi there, 

I'm using your file checker for FDF and it tell me that declarations of static functions that I have prototyped on top of the file are forbidden, when actually they pass the norminette and everything compiles. The file checker says those files are OK when I put my static functions first instead of putting them after more relevant functions and prototyping them. ie:

This does not work:
> static void foo ();
> 
> void otherfunction()
> {
> }
> 
> static void foo()
> {
> }

But this works:
> static void foo()
> {
> }
> void otherfunction()
> {
> }

Is this intentional?

Thanks!

**Comment by jgigault** [comment]
Hello!
And thanks for your issue, and sorry for my late answer..
It is not intentional because I did not think about that use case.
Let me discuss with my colleagues and I will fix it

**Comment by anouvel** [comment]
Hi @jgigault and @JanWalsh91 !

- Firstly, it is nothing kind of bad practices for both cases. Some people want to have there functions declaration before the 'main' function and the implementation after: 

```C
void f(void);

int  main(void) { f(); return (0); }

void f(void) { printf("hello\n"); }
```

and other:

```C
void f(void) { printf("hello\n"); }

int  main(void) { f(); return (0); }
```

- About the static keyword in this type of usage, please read it http://stackoverflow.com/questions/15670010/does-a-static-function-need-the-static-keyword-for-the-prototype-in-c and http://stackoverflow.com/questions/8972319/prototypes-for-static-functions , it seems to be a good practice in case of complex function calls (static A call static B call static A) but should introduce some complex compilation errors. And my opinion (even if I don't often use this kind of structure) is that it is a good practice regarding as the common structure of a C project (external prototypes in headers and implementation in files, internal prototypes and implementation in files).

- So, yes, I think that 42FC should accept this behaviour.

**Comment by jgigault** [comment]
Thanks for your review @anouvel :-)
