### ISSUE TITLE
Rajouter un fichier test pour le fillit

### ISSUE THREAD

**Issue by Bux42** [jgigault/42FileChecker#82]
Hello

Je me suis rendu compte que le fillit checker ne vérifiait le cas ou les points étaient remplacés par d'autre caractères!

Voili voilu, et merki pour tout

**Comment by jgigault** [comment]
Salut,

Est-ce que ton "issue" est toujours d'actualité ? 
Est-ce que le fillit_checker prend ce cas en compte ?
