### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by alekseykpi** [jgigault/42FileChecker#86]
I am getting "Couldn't get a file descriptor referring to the console" when I want to get tests description or any other option after tests

**Comment by jgigault** [comment]
Hello
Can you describe your running environment? (School, installation directory of 42Fc)

**Comment by alekseykpi** [comment]
Hi. It's virtual machine with Ubuntu 16.04 on my  laptop. Directory is Home\42FileChecker

**Comment by atenagm** [comment]
same problem on ubuntu 16.04

**Comment by Seluj78** [comment]
If you are using a non desktop environment or just Ubuntu bash for Windows it's supposed to happen

**Comment by Seluj78** [comment]
So, to give a little more context before closing this:

The executable that is `spitting` out this error is called `open`. For example, on Darwin (`MacOSX`), if you type in your terminal `open index.html`, it'll open the `index.html` file on your default browser. This also works on an installed version on linux, a hardware one (Doesnt work for `Virtual Machines` and `Ubuntu Bash for Windows`).

**Comment by Karocyt** [comment]
Doen't work on 17.10 / 18.04 either, as a full Desktop AMD64 version. "open-xdg" does the same, but Ubuntu doesn't has "open" builtin anymore.
