### ISSUE TITLE
Doesn't like the location of my libft and the way i include...

### ISSUE THREAD

**Issue by Seluj78** [jgigault/42FileChecker#87]
`make exec_tests
..echo "tests/00_test_without_opt.spec.c tests/01_test_opt_R.spec.c tests/02_test_sorted.spec.c tests/03_test_multiple_dir.spec.c tests/04_test_opt_a.spec.c tests/05_test_opt_r.spec.c tests/06_test_opt_rR.spec.c tests/07_test_opt_t.spec.c tests/07_test_opt_tR_bis.spec.c tests/08_test_opt_l.spec.c tests/09_test_opt_aR.spec.c tests/10_test_opt_aRl.spec.c tests/11_test_single_file.spec.c tests/12_test_permissions.spec.c tests/13_test_hyphen_hard.spec.c tests/14_test_hyphen_harder.spec.c tests/20_test_error_handling.spec.c tests/21_test_symlink.spec.c tests/22_test_no_username.spec.c tests/23_test_no_groupname.spec.c tests/24_test_multiple_files.spec.c tests/25_perm_special_bits.spec.c tests/26_perm_special_bits_dir.spec.c tests/30_test_opt_mix.spec.c tests/bonus_01_test_opt_d.spec.c tests/bonus_02_test_opt_p.spec.c tests/bonus_03_test_opt_U.spec.c tests/bonus_04_test_opt_c.spec.c tests/bonus_05_test_opt_S.spec.c tests/bonus_06_test_opt_u.spec.c tests/bonus_07_test_opt_A.spec.c tests/bonus_08_test_opt_1.spec.c tests/bonus_09_test_opt_f.spec.c tests/bonus_10_test_opt_T.spec.c tests/bonus_11_test_opt_g.spec.c tests/bonus_12_test_opt_o_og.spec.c tests/bonus_13_test_opt_F_Fp.spec.c tests/bonus_20_test_opt_comb_aA.spec.c tests/bonus_21_test_opt_mix_sort.spec.c tests/bonus_22_test_sort_comb.spec.c tests/bonus_30_test_xattr.spec.c tests/bonus_31_test_usr_xattr.spec.c tests/bonus_32_test_ACL.spec.c tests/bonus_34_test_redis.spec.c tests/bonus_40_dir_root.spec.c tests/sys_00_test_user_bin.spec.c tests/sys_01_test_dev.spec.c tests/sys_02_test_etc.spec.c tests/sys_03_test_many_files.spec.c tests/sys_04_test_var_run.spec.c"
tests/00_test_without_opt.spec.c tests/01_test_opt_R.spec.c tests/02_test_sorted.spec.c tests/03_test_multiple_dir.spec.c tests/04_test_opt_a.spec.c tests/05_test_opt_r.spec.c tests/06_test_opt_rR.spec.c tests/07_test_opt_t.spec.c tests/07_test_opt_tR_bis.spec.c tests/08_test_opt_l.spec.c tests/09_test_opt_aR.spec.c tests/10_test_opt_aRl.spec.c tests/11_test_single_file.spec.c tests/12_test_permissions.spec.c tests/13_test_hyphen_hard.spec.c tests/14_test_hyphen_harder.spec.c tests/20_test_error_handling.spec.c tests/21_test_symlink.spec.c tests/22_test_no_username.spec.c tests/23_test_no_groupname.spec.c tests/24_test_multiple_files.spec.c tests/25_perm_special_bits.spec.c tests/26_perm_special_bits_dir.spec.c tests/30_test_opt_mix.spec.c tests/bonus_01_test_opt_d.spec.c tests/bonus_02_test_opt_p.spec.c tests/bonus_03_test_opt_U.spec.c tests/bonus_04_test_opt_c.spec.c tests/bonus_05_test_opt_S.spec.c tests/bonus_06_test_opt_u.spec.c tests/bonus_07_test_opt_A.spec.c tests/bonus_08_test_opt_1.spec.c tests/bonus_09_test_opt_f.spec.c tests/bonus_10_test_opt_T.spec.c tests/bonus_11_test_opt_g.spec.c tests/bonus_12_test_opt_o_og.spec.c tests/bonus_13_test_opt_F_Fp.spec.c tests/bonus_20_test_opt_comb_aA.spec.c tests/bonus_21_test_opt_mix_sort.spec.c tests/bonus_22_test_sort_comb.spec.c tests/bonus_30_test_xattr.spec.c tests/bonus_31_test_usr_xattr.spec.c tests/bonus_32_test_ACL.spec.c tests/bonus_34_test_redis.spec.c tests/bonus_40_dir_root.spec.c tests/sys_00_test_user_bin.spec.c tests/sys_01_test_dev.spec.c tests/sys_02_test_etc.spec.c tests/sys_03_test_many_files.spec.c tests/sys_04_test_var_run.spec.c
make re -k -C /Users/jlasne/ft_ls/libft
rm -f ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o ft_memmove.o ft_memchr.o ft_memcmp.o ft_memalloc.o ft_memdel.o ft_strlen.o ft_strdup.o ft_strcpy.o ft_strncpy.o ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o ft_strncmp.o ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_lstmap.o ft_itoa.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_lstnew.o ft_nblen.o
rm -f libft.a
gcc -Wall -Wextra -Werror -c ft_memset.c ft_bzero.c ft_memcpy.c  ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_memalloc.c ft_memdel.c ft_strlen.c ft_strdup.c ft_strcpy.c ft_strncpy.c ft_strcat.c ft_strncat.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_lstmap.c ft_itoa.c ft_lstdelone.c ft_lstdel.c ft_lstadd.c ft_lstiter.c ft_putchar.c ft_putstr.c ft_putendl.c ft_putnbr.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_lstnew.c ft_nblen.c -I libft.h
ar rc libft.a ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o ft_memmove.o ft_memchr.o ft_memcmp.o ft_memalloc.o ft_memdel.o ft_strlen.o ft_strdup.o ft_strcpy.o ft_strncpy.o ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o ft_strncmp.o ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_lstmap.o ft_itoa.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_lstnew.o ft_nblen.o
make re -k -C /Users/jlasne/ft_ls -L /Users/jlasne/ft_ls/libft -lft
rm -rf parser.o additional_func.o additional_func2.o gestion.o main.o gestion_l.o ls_perms.o user_info.o
make clean -C ./libft/
rm -f ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o ft_memmove.o ft_memchr.o ft_memcmp.o ft_memalloc.o ft_memdel.o ft_strlen.o ft_strdup.o ft_strcpy.o ft_strncpy.o ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o ft_strncmp.o ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_lstmap.o ft_itoa.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_lstnew.o ft_nblen.o
rm -rf ft_ls
make fclean -C ./libft/
rm -f ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o ft_memmove.o ft_memchr.o ft_memcmp.o ft_memalloc.o ft_memdel.o ft_strlen.o ft_strdup.o ft_strcpy.o ft_strncpy.o ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o ft_strncmp.o ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_lstmap.o ft_itoa.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_lstnew.o ft_nblen.o
rm -f libft.a
clang -o parser.o -c srcs//parser.c -Wall -Wextra -Werror
clang -o additional_func.o -c srcs//additional_func.c -Wall -Wextra -Werror
clang -o additional_func2.o -c srcs//additional_func2.c -Wall -Wextra -Werror
clang -o gestion.o -c srcs//gestion.c -Wall -Wextra -Werror
clang -o main.o -c srcs//main.c -Wall -Wextra -Werror
clang -o gestion_l.o -c srcs//gestion_l.c -Wall -Wextra -Werror
clang -o ls_perms.o -c srcs//ls_perms.c -Wall -Wextra -Werror
clang -o user_info.o -c srcs//user_info.c -Wall -Wextra -Werror
make -C ./libft/
gcc -Wall -Wextra -Werror -c ft_memset.c ft_bzero.c ft_memcpy.c  ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_memalloc.c ft_memdel.c ft_strlen.c ft_strdup.c ft_strcpy.c ft_strncpy.c ft_strcat.c ft_strncat.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_lstmap.c ft_itoa.c ft_lstdelone.c ft_lstdel.c ft_lstadd.c ft_lstiter.c ft_putchar.c ft_putstr.c ft_putendl.c ft_putnbr.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_lstnew.c ft_nblen.c -I libft.h
ar rc libft.a ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o ft_memmove.o ft_memchr.o ft_memcmp.o ft_memalloc.o ft_memdel.o ft_strlen.o ft_strdup.o ft_strcpy.o ft_strncpy.o ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o ft_strncmp.o ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_lstmap.o ft_itoa.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_lstnew.o ft_nblen.o
clang -Wall -Wextra -Werror parser.o additional_func.o additional_func2.o gestion.o main.o gestion_l.o ls_perms.o user_info.o -o ft_ls libft/libft.a
make[3]: Nothing to be done for `/Users/jlasne/ft_ls/libft'.
make -k -C ../testframework/v3/
rm -f *.o
cc -Wall -Werror -Wextra -ggdb -I includes -c srcs/**/*.c
ar rc libmt_framework.a *.o
cc -g -I . -I ../testframework/v3//includes -I /Users/jlasne/ft_ls -I /Users/jlasne/ft_ls/includes -I /Users/jlasne/ft_ls/includes/builtin -I /Users/jlasne/ft_ls/libs/libtowel/includes -I /Users/jlasne/ft_ls/libft/includes -I /Users/jlasne/ft_ls/srcs/libft/includes -D__MOULITEST__ -DPROTOTYPES="MT_ADD_PROTO(00_test_without_opt); MT_ADD_PROTO(01_test_opt_R); MT_ADD_PROTO(02_test_sorted); MT_ADD_PROTO(03_test_multiple_dir); MT_ADD_PROTO(04_test_opt_a); MT_ADD_PROTO(05_test_opt_r); MT_ADD_PROTO(06_test_opt_rR); MT_ADD_PROTO(07_test_opt_t); MT_ADD_PROTO(07_test_opt_tR_bis); MT_ADD_PROTO(08_test_opt_l); MT_ADD_PROTO(09_test_opt_aR); MT_ADD_PROTO(10_test_opt_aRl); MT_ADD_PROTO(11_test_single_file); MT_ADD_PROTO(12_test_permissions); MT_ADD_PROTO(13_test_hyphen_hard); MT_ADD_PROTO(14_test_hyphen_harder); MT_ADD_PROTO(20_test_error_handling); MT_ADD_PROTO(21_test_symlink); MT_ADD_PROTO(22_test_no_username); MT_ADD_PROTO(23_test_no_groupname); MT_ADD_PROTO(24_test_multiple_files); MT_ADD_PROTO(25_perm_special_bits); MT_ADD_PROTO(26_perm_special_bits_dir); MT_ADD_PROTO(30_test_opt_mix); MT_ADD_PROTO(bonus_01_test_opt_d); MT_ADD_PROTO(bonus_02_test_opt_p); MT_ADD_PROTO(bonus_03_test_opt_U); MT_ADD_PROTO(bonus_04_test_opt_c); MT_ADD_PROTO(bonus_05_test_opt_S); MT_ADD_PROTO(bonus_06_test_opt_u); MT_ADD_PROTO(bonus_07_test_opt_A); MT_ADD_PROTO(bonus_08_test_opt_1); MT_ADD_PROTO(bonus_09_test_opt_f); MT_ADD_PROTO(bonus_10_test_opt_T); MT_ADD_PROTO(bonus_11_test_opt_g); MT_ADD_PROTO(bonus_12_test_opt_o_og); MT_ADD_PROTO(bonus_13_test_opt_F_Fp); MT_ADD_PROTO(bonus_20_test_opt_comb_aA); MT_ADD_PROTO(bonus_21_test_opt_mix_sort); MT_ADD_PROTO(bonus_22_test_sort_comb); MT_ADD_PROTO(bonus_30_test_xattr); MT_ADD_PROTO(bonus_31_test_usr_xattr); MT_ADD_PROTO(bonus_32_test_ACL); MT_ADD_PROTO(bonus_34_test_redis); MT_ADD_PROTO(bonus_40_dir_root); MT_ADD_PROTO(sys_00_test_user_bin); MT_ADD_PROTO(sys_01_test_dev); MT_ADD_PROTO(sys_02_test_etc); MT_ADD_PROTO(sys_03_test_many_files); MT_ADD_PROTO(sys_04_test_var_run); " -DADD_TESTS="MT_ADD_SUITE(mt, 00_test_without_opt, suite_00_test_without_opt); MT_ADD_SUITE(mt, 01_test_opt_R, suite_01_test_opt_R); MT_ADD_SUITE(mt, 02_test_sorted, suite_02_test_sorted); MT_ADD_SUITE(mt, 03_test_multiple_dir, suite_03_test_multiple_dir); MT_ADD_SUITE(mt, 04_test_opt_a, suite_04_test_opt_a); MT_ADD_SUITE(mt, 05_test_opt_r, suite_05_test_opt_r); MT_ADD_SUITE(mt, 06_test_opt_rR, suite_06_test_opt_rR); MT_ADD_SUITE(mt, 07_test_opt_t, suite_07_test_opt_t); MT_ADD_SUITE(mt, 07_test_opt_tR_bis, suite_07_test_opt_tR_bis); MT_ADD_SUITE(mt, 08_test_opt_l, suite_08_test_opt_l); MT_ADD_SUITE(mt, 09_test_opt_aR, suite_09_test_opt_aR); MT_ADD_SUITE(mt, 10_test_opt_aRl, suite_10_test_opt_aRl); MT_ADD_SUITE(mt, 11_test_single_file, suite_11_test_single_file); MT_ADD_SUITE(mt, 12_test_permissions, suite_12_test_permissions); MT_ADD_SUITE(mt, 13_test_hyphen_hard, suite_13_test_hyphen_hard); MT_ADD_SUITE(mt, 14_test_hyphen_harder, suite_14_test_hyphen_harder); MT_ADD_SUITE(mt, 20_test_error_handling, suite_20_test_error_handling); MT_ADD_SUITE(mt, 21_test_symlink, suite_21_test_symlink); MT_ADD_SUITE(mt, 22_test_no_username, suite_22_test_no_username); MT_ADD_SUITE(mt, 23_test_no_groupname, suite_23_test_no_groupname); MT_ADD_SUITE(mt, 24_test_multiple_files, suite_24_test_multiple_files); MT_ADD_SUITE(mt, 25_perm_special_bits, suite_25_perm_special_bits); MT_ADD_SUITE(mt, 26_perm_special_bits_dir, suite_26_perm_special_bits_dir); MT_ADD_SUITE(mt, 30_test_opt_mix, suite_30_test_opt_mix); MT_ADD_SUITE(mt, bonus_01_test_opt_d, suite_bonus_01_test_opt_d); MT_ADD_SUITE(mt, bonus_02_test_opt_p, suite_bonus_02_test_opt_p); MT_ADD_SUITE(mt, bonus_03_test_opt_U, suite_bonus_03_test_opt_U); MT_ADD_SUITE(mt, bonus_04_test_opt_c, suite_bonus_04_test_opt_c); MT_ADD_SUITE(mt, bonus_05_test_opt_S, suite_bonus_05_test_opt_S); MT_ADD_SUITE(mt, bonus_06_test_opt_u, suite_bonus_06_test_opt_u); MT_ADD_SUITE(mt, bonus_07_test_opt_A, suite_bonus_07_test_opt_A); MT_ADD_SUITE(mt, bonus_08_test_opt_1, suite_bonus_08_test_opt_1); MT_ADD_SUITE(mt, bonus_09_test_opt_f, suite_bonus_09_test_opt_f); MT_ADD_SUITE(mt, bonus_10_test_opt_T, suite_bonus_10_test_opt_T); MT_ADD_SUITE(mt, bonus_11_test_opt_g, suite_bonus_11_test_opt_g); MT_ADD_SUITE(mt, bonus_12_test_opt_o_og, suite_bonus_12_test_opt_o_og); MT_ADD_SUITE(mt, bonus_13_test_opt_F_Fp, suite_bonus_13_test_opt_F_Fp); MT_ADD_SUITE(mt, bonus_20_test_opt_comb_aA, suite_bonus_20_test_opt_comb_aA); MT_ADD_SUITE(mt, bonus_21_test_opt_mix_sort, suite_bonus_21_test_opt_mix_sort); MT_ADD_SUITE(mt, bonus_22_test_sort_comb, suite_bonus_22_test_sort_comb); MT_ADD_SUITE(mt, bonus_30_test_xattr, suite_bonus_30_test_xattr); MT_ADD_SUITE(mt, bonus_31_test_usr_xattr, suite_bonus_31_test_usr_xattr); MT_ADD_SUITE(mt, bonus_32_test_ACL, suite_bonus_32_test_ACL); MT_ADD_SUITE(mt, bonus_34_test_redis, suite_bonus_34_test_redis); MT_ADD_SUITE(mt, bonus_40_dir_root, suite_bonus_40_dir_root); MT_ADD_SUITE(mt, sys_00_test_user_bin, suite_sys_00_test_user_bin); MT_ADD_SUITE(mt, sys_01_test_dev, suite_sys_01_test_dev); MT_ADD_SUITE(mt, sys_02_test_etc, suite_sys_02_test_etc); MT_ADD_SUITE(mt, sys_03_test_many_files, suite_sys_03_test_many_files); MT_ADD_SUITE(mt, sys_04_test_var_run, suite_sys_04_test_var_run); " -DRENDU_PATH="\"/Users/jlasne/ft_ls\"" tests/00_test_without_opt.spec.c tests/01_test_opt_R.spec.c tests/02_test_sorted.spec.c tests/03_test_multiple_dir.spec.c tests/04_test_opt_a.spec.c tests/05_test_opt_r.spec.c tests/06_test_opt_rR.spec.c tests/07_test_opt_t.spec.c tests/07_test_opt_tR_bis.spec.c tests/08_test_opt_l.spec.c tests/09_test_opt_aR.spec.c tests/10_test_opt_aRl.spec.c tests/11_test_single_file.spec.c tests/12_test_permissions.spec.c tests/13_test_hyphen_hard.spec.c tests/14_test_hyphen_harder.spec.c tests/20_test_error_handling.spec.c tests/21_test_symlink.spec.c tests/22_test_no_username.spec.c tests/23_test_no_groupname.spec.c tests/24_test_multiple_files.spec.c tests/25_perm_special_bits.spec.c tests/26_perm_special_bits_dir.spec.c tests/30_test_opt_mix.spec.c tests/bonus_01_test_opt_d.spec.c tests/bonus_02_test_opt_p.spec.c tests/bonus_03_test_opt_U.spec.c tests/bonus_04_test_opt_c.spec.c tests/bonus_05_test_opt_S.spec.c tests/bonus_06_test_opt_u.spec.c tests/bonus_07_test_opt_A.spec.c tests/bonus_08_test_opt_1.spec.c tests/bonus_09_test_opt_f.spec.c tests/bonus_10_test_opt_T.spec.c tests/bonus_11_test_opt_g.spec.c tests/bonus_12_test_opt_o_og.spec.c tests/bonus_13_test_opt_F_Fp.spec.c tests/bonus_20_test_opt_comb_aA.spec.c tests/bonus_21_test_opt_mix_sort.spec.c tests/bonus_22_test_sort_comb.spec.c tests/bonus_30_test_xattr.spec.c tests/bonus_31_test_usr_xattr.spec.c tests/bonus_32_test_ACL.spec.c tests/bonus_34_test_redis.spec.c tests/bonus_40_dir_root.spec.c tests/sys_00_test_user_bin.spec.c tests/sys_01_test_dev.spec.c tests/sys_02_test_etc.spec.c tests/sys_03_test_many_files.spec.c tests/sys_04_test_var_run.spec.c main.c utils.c  .tmp/objects/additional_func.o .tmp/objects/additional_func2.o .tmp/objects/gestion.o .tmp/objects/gestion_l.o .tmp/objects/ls_perms.o .tmp/objects/main.o .tmp/objects/parser.o .tmp/objects/user_info.o -o ft_ls_test -L../testframework/v3/ -lmt_framework 
Undefined symbols for architecture x86_64:
  "_ft_nblen", referenced from:
      _save_ls in gestion.o
      _show_l in gestion_l.o
     (maybe you meant: _ft_nblen_ll)
  "_ft_putchar", referenced from:
      _printspaces in additional_func.o
      _ft_putnbr_ll in additional_func2.o
      _show in gestion.o
      _show_l in gestion_l.o
      _print_time in gestion_l.o
      _wrong_flags in parser.o
      _print_user_info in user_info.o
      ...
  "_ft_putendl", referenced from:
      _save_ls in gestion.o
      _wrong_flags in parser.o
  "_ft_putnbr", referenced from:
      _show_l in gestion_l.o
      _print_majorminor in gestion_l.o
     (maybe you meant: _ft_putnbr_ll)
  "_ft_putstr", referenced from:
      _ft_putnbr_ll in additional_func2.o
      _show in gestion.o
      _show_l in gestion_l.o
      _print_majorminor in gestion_l.o
      _print_time in gestion_l.o
      _printfile in gestion_l.o
      _lsperms in ls_perms.o
      ...
  "_ft_strchr", referenced from:
      _arg_parser in parser.o
  "_ft_strcmp", referenced from:
      _addtoshow in gestion.o
      _trithat in gestion.o
  "_ft_strcpy", referenced from:
      _lsperms in ls_perms.o
  "_ft_strdup", referenced from:
      _save_ls in gestion.o
  "_ft_strlen", referenced from:
      _ft_strjoin_sep in additional_func.o
      _save_ls in gestion.o
      _ft_joinpath in gestion.o
      _print_time in gestion_l.o
      _print_user_info in user_info.o
      _print_user_group in user_info.o
  "_ft_strnew", referenced from:
      _print_time in gestion_l.o
  "_ft_strsub", referenced from:
      _print_time in gestion_l.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [exec_tests] Error 1
make[1]: *** [all] Error 2
make: *** [ft_ls] Error 2
`

**Comment by jgigault** [comment]
It seems to be a moulitest issue, isn't it?

**Comment by Seluj78** [comment]
yep I think so
