### ISSUE TITLE
Norminettte OK mais 42FileChecker détecte une erreur

### ISSUE THREAD

**Issue by kklleemm** [jgigault/42FileChecker#9]
5 -> norminette
1 error(s) or warning(s)

**Comment by jgigault** [comment]
Hello,
Can you please show me what's output when you run `norminette your_project_directory/` ?

**Comment by kklleemm** [comment]
coucou jeanmi, c'est cdeniau :)
J'ai ça : (et je suis pas le seul a avoir le pb)
e2r11p20% norminette libft
Norme: ./libft/Makefile
Warning: Not a valid file
Norme: ./libft/auteur
Warning: Not a valid file
Norme: ./libft/ft_memchr.c
Norme: ./libft/libft_struct.h
Norme: ./libft/ft_strlen.c
Norme: ./libft/ft_strcat.c
Norme: ./libft/ft_memset.c
Norme: ./libft/ft_strstr.c
Norme: ./libft/ft_strjoin.c
Norme: ./libft/ft_strlcpy.c
Norme: ./libft/ft_strnequ.c
Norme: ./libft/ft_print_mem.c
Norme: ./libft/ft_strrchr.c
Norme: ./libft/ft_strmapi.c
Norme: ./libft/ft_abs.c
Norme: ./libft/list.c
Norme: ./libft/ft_striter.c
Norme: ./libft/ft_lstiter.c
Norme: ./libft/ft_power.c
Norme: ./libft/ft_atoi_hex.c
Norme: ./libft/ft_lstdel.c
Norme: ./libft/ft_memdel.c
Norme: ./libft/ft_memalloc.c
Norme: ./libft/ft_atoi.c
Norme: ./libft/ft_putchar_fd.c
Norme: ./libft/ft_strlcat.c
Norme: ./libft/ft_tolower.c
Norme: ./libft/ft_putstr_fd.c
Norme: ./libft/ft_tan.c
Norme: ./libft/ft_cos.c
Norme: ./libft/ft_bzero.c
Norme: ./libft/ft_fact.c
Norme: ./libft/ft_strclr.c
Norme: ./libft/ft_strnstr.c
Norme: ./libft/ft_strncpy.c
Norme: ./libft/ft_striteri.c
Norme: ./libft/ft_putendl_fd.c
Norme: ./libft/ft_putchar.c
Norme: ./libft/ft_strncmp.c
Norme: ./libft/ft_strsplit.c
Norme: ./libft/count_island.c
Norme: ./libft/ft_lstmap.c
Norme: ./libft/ft_isascii.c
Norme: ./libft/ft_strmap.c
Norme: ./libft/ft_putnbr_fd.c
Norme: ./libft/ft_strdup.c
Norme: ./libft/ft_isalpha.c
Norme: ./libft/ft_strcpy.c
Norme: ./libft/ft_strdel.c
Norme: ./libft/ft_memmove.c
Norme: ./libft/ft_putnbr.c
Norme: ./libft/ft_memcmp.c
Norme: ./libft/ft_putendl.c
Norme: ./libft/ft_toupper.c
Norme: ./libft/ft_strtrim.c
Norme: ./libft/ft_memccpy.c
Norme: ./libft/ft_errno.c
Norme: ./libft/ft_isprint.c
Norme: ./libft/ft_strequ.c
Norme: ./libft/ft_itoa.c
Norme: ./libft/ft_strsub.c
Norme: ./libft/ft_strcmp.c
Norme: ./libft/ft_memcpy.c
Norme: ./libft/get_next_line.h
Norme: ./libft/ft_strnew.c
Norme: ./libft/ft_lstadd.c
Norme: ./libft/get_next_line.c
Norme: ./libft/ft_isalnum.c
Norme: ./libft/ft_putstr.c
Norme: ./libft/ft_lstnew.c
Norme: ./libft/ft_strncat.c
Norme: ./libft/ft_lstdelone.c
Norme: ./libft/ft_isdigit.c
Norme: ./libft/ft_strchr.c
Norme: ./libft/libft.h

**Comment by jgigault** [comment]
Hello Clément :-) et merci d'avoir ouvert cette issue !

Peux-tu lancer ceci stp (même si ça parait bête) ?
```bash
norminette ./libft/ft_memchr.c ./libft/libft_struct.h ./libft/ft_strlen.c ./libft/ft_strcat.c ./libft/ft_memset.c ./libft/ft_strstr.c ./libft/ft_strjoin.c ./libft/ft_strlcpy.c ./libft/ft_strnequ.c ./libft/ft_print_mem.c ./libft/ft_strrchr.c ./libft/ft_strmapi.c ./libft/ft_abs.c ./libft/list.c ./libft/ft_striter.c ./libft/ft_lstiter.c ./libft/ft_power.c ./libft/ft_atoi_hex.c ./libft/ft_lstdel.c ./libft/ft_memdel.c ./libft/ft_memalloc.c ./libft/ft_atoi.c ./libft/ft_putchar_fd.c ./libft/ft_strlcat.c ./libft/ft_tolower.c ./libft/ft_putstr_fd.c ./libft/ft_tan.c ./libft/ft_cos.c ./libft/ft_bzero.c ./libft/ft_fact.c ./libft/ft_strclr.c ./libft/ft_strnstr.c ./libft/ft_strncpy.c ./libft/ft_striteri.c ./libft/ft_putendl_fd.c ./libft/ft_putchar.c ./libft/ft_strncmp.c ./libft/ft_strsplit.c ./libft/count_island.c ./libft/ft_lstmap.c ./libft/ft_isascii.c ./libft/ft_strmap.c ./libft/ft_putnbr_fd.c ./libft/ft_strdup.c ./libft/ft_isalpha.c ./libft/ft_strcpy.c ./libft/ft_strdel.c ./libft/ft_memmove.c ./libft/ft_putnbr.c ./libft/ft_memcmp.c ./libft/ft_putendl.c ./libft/ft_toupper.c ./libft/ft_strtrim.c ./libft/ft_memccpy.c ./libft/ft_errno.c ./libft/ft_isprint.c ./libft/ft_strequ.c ./libft/ft_itoa.c ./libft/ft_strsub.c ./libft/ft_strcmp.c ./libft/ft_memcpy.c ./libft/get_next_line.h ./libft/ft_strnew.c ./libft/ft_lstadd.c ./libft/get_next_line.c ./libft/ft_isalnum.c ./libft/ft_putstr.c ./libft/ft_lstnew.c ./libft/ft_strncat.c ./libft/ft_lstdelone.c ./libft/ft_isdigit.c ./libft/ft_strchr.c ./libft/libft.h
```

C'est à priori ce que fait mon script avec ton dossier, voir la liste des instructions:
```bash
LIST=$(find . -type f | sed '/^\.\/\./d' | grep -E \\.\[hc\]$ | tr '\n' ' ') #liste tous les fichiers *.c et *.h
RESULT=$(norminette $LIST 2>&1) #lance la norminette et récupère le résultat dans une variable
echo $RESULT | grep Error
echo $RESULT | grep Warning
echo $RESULT | grep "command not found"
```

Est-ce une histoire de cache de la nouvelle norminette ?
Ça fail "tout le temps" ou bien est-ce que c'est "souvent" ?

**Comment by dcognata** [comment]
de meme, quand je lance ta commande ca test les autres projets en norme.

**Comment by jgigault** [comment]
Salut @dcognata
Pourrais-tu faire ´ cat .mynorminette ´  après avoir lancé le checker et quitté.
Merci d'avance

**Comment by jgigault** [comment]
Et me donner le résultat :p

**Comment by dcognata** [comment]
Current configuration:                                                                                                                                                                                                                                                                                                                                          LIBFT    ~/libft

  1 -> auteur
  dcognata$

  2 -> required functions
  All files were found

  3 -> bonus
  All files were found

  4 -> extra functions
  6 extra functions were found

  5 -> norminette
  All files passed the tests

  6 -> static declarations
  All auxiliary functions are declared as static

  7 -> makefile
  Makefile seems to work perfectly

  8 -> forbidden functions
  No forbidden function found

  9 -> moulitest (https://github.com/yyang42/moulitest_42projects)
  All Unit Tests passed


Du coup je pense que c'est un soucis hors du programme, ticket a close. :+1:

**Comment by jgigault** [comment]
OK merci.
Toutefois il semblerait que les messages d'erreur quand la norme n'est pas respectée aient changé. Dans le doute je garde une issue ouverte et je closerai en janvier à mon retour.

**Comment by lpoujade** [comment]
yop, meme probleme ici ( {liste des fichiers} : not a valid file )
Dans le script ( utils.sh ) j ai vire les " " autour du nom de variables des fichiers et ca a marche par contre
( je fais une pull request pour que tu vois ou je veut dire )

**Comment by jgigault** [comment]
This issue should have been fixed with PR #17.
