### ISSUE TITLE
Rechecking Bug

### ISSUE THREAD

**Issue by Muzgul** [jgigault/42FileChecker#93]
There is an issue when testing the libft. After doing the unit tests, redoing the test result in a Fatal Error claiming compile issues. The information page shows no errors in compiling my code, rather an issue in renaming the temp files that 42FileChecker uses. This is frustrating as I have no idea how to reset other than restarting the File checker but that doesn't always result in a fix.

**Comment by Seluj78** [comment]
Well, if you could provide an update on that or a screenshot that would've helped :D

**Comment by Seluj78** [comment]
@Muzgul Can we have screenshots and error logs please ? 

I'm closing the issue meanwhile.
