### ISSUE TITLE
Debug libft bonus part

### ISSUE THREAD

**Issue by CallMarl** [jgigault/42FileChecker#98]
Hello, 
I past a lot of time to debug ft_lstnew() with 42FileChecker, in fact in the header file struct must exactly the same as the subject for all the bonus part test. I don't know if it's done on prupose.

**Comment by Seluj78** [comment]
If I understand you correctly, Then yes, it's done on purpose. The libft project, when you are doing it, you're supposed to follow everything they say, including the struct in the header file for chained lists.

But now that you've finished the libft, you can do whatever you want to do
